/**
 * The report renderer — turns a run (and an optional comparison) into the two
 * tracked artifacts: a human `RESULTS.md` table and a machine `results.json`.
 * Pure string/JSON production, no I/O; the bin writes what these return.
 */

import type { Comparison, ResultsByName, WorkloadDelta } from "./compare";
import type { RunResult } from "./runner";

/** A full report: the run's results, when it was taken, and the harness version. */
export interface Report {
  /** ISO-8601 timestamp the run was recorded at. */
  readonly recordedAt: string;
  /** The git/release ref the run measured, if the caller knows it. */
  readonly ref?: string;
  readonly results: ResultsByName;
}

/** Round to two decimals for stable, diff-friendly output (no 17-digit float tails). */
function round2(value: number): number {
  return Math.round(value * 100) / 100;
}

/**
 * Round to four decimals for the latency columns. Sub-millisecond medians are
 * common in-process — at two decimals a real `0.0027ms` p50 renders as a
 * misleading `0`, so the ms columns get the extra precision.
 */
function round4(value: number): number {
  return Math.round(value * 10_000) / 10_000;
}

/** Format a fractional delta as a signed percentage, or `—` when there is no baseline. */
function formatDelta(delta: number | null): string {
  if (delta === null) {
    return "—";
  }

  const pct = round2(delta * 100);

  // A leading `+` on non-negative deltas so a glance reads direction without
  // hunting for a sign; `-` comes from the number itself. `+0` for an exact zero
  // is fine — it still reads "no change, measured."
  return `${pct >= 0 ? "+" : ""}${pct}%`;
}

/** The verdict as a glance-able marker for the markdown table. */
function verdictMark(delta: WorkloadDelta): string {
  switch (delta.verdict) {
    case "improved":
      return "up";
    case "regressed":
      return "down";
    case "new":
      return "new";
    case "unchanged":
      return "flat";
  }
}

/**
 * Render the tracked markdown report. Deterministic and stable: rows are sorted
 * by workload name and numbers are rounded, so re-running with the same inputs
 * produces a byte-identical file (a noisy diff would defeat tracking). When a
 * `comparison` is supplied, two trend columns (Δ req/s, Δ p99) and a verdict
 * marker are appended so the file shows movement, not just a snapshot.
 */
export function renderMarkdown(report: Report, comparison?: Comparison): string {
  const deltaByName = new Map((comparison?.deltas ?? []).map((delta) => [delta.name, delta]));
  const rows = Object.values(report.results).toSorted((a, b) => a.name.localeCompare(b.name));

  const header = comparison
    ? "| Workload | req/s | p50 (ms) | p99 (ms) | n | conc | Δ req/s | Δ p99 | |"
    : "| Workload | req/s | p50 (ms) | p99 (ms) | n | conc |";
  const rule = comparison
    ? "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | :---: |"
    : "| --- | ---: | ---: | ---: | ---: | ---: |";

  const body = rows.map((run) => {
    const base =
      `| ${run.name} | ${round2(run.stats.throughput)} | ${round4(run.stats.p50)} | ` +
      `${round4(run.stats.p99)} | ${run.iterations} | ${run.concurrency} |`;

    if (!comparison) {
      return base;
    }

    // Every row in `report.results` was diffed by `compareRuns` (the deltas ARE
    // the current run's results), so every name has a delta — the assertion is a
    // real invariant, not a guess, and avoids a dead `undefined` branch the
    // 100%-branch gate could never cover.
    const delta = deltaByName.get(run.name) as WorkloadDelta;

    return (
      `${base} ${formatDelta(delta.throughputDelta)} | ` +
      `${formatDelta(delta.p99Delta)} | ${verdictMark(delta)} |`
    );
  });

  const regressionNote =
    comparison && comparison.regressed
      ? "\n> A workload regressed beyond the threshold versus the recorded baseline.\n"
      : "";

  const refLine = report.ref ? `\n_ref: \`${report.ref}\`_\n` : "";

  return [
    "# Lesto benchmark results",
    "",
    "Generated by `@lesto/bench`. These are volatile in-process micro-benchmarks:",
    "self-vs-self noise routinely runs tens of percent, so read the trend as a",
    "rough signal, never the absolutes — and never across machines.",
    "",
    `_recorded: ${report.recordedAt}_`,
    refLine,
    header,
    rule,
    ...body,
    regressionNote,
  ]
    .filter((line) => line !== "")
    .join("\n")
    .concat("\n");
}

/**
 * Render the machine artifact — pretty-printed JSON with sorted keys, so the
 * committed `results.json` diffs cleanly and the next run's compare reads a
 * canonical shape. This is the file `compareRuns` consumes as its baseline.
 */
export function renderJson(report: Report): string {
  const sortedResults: Record<string, RunResult> = {};
  for (const name of Object.keys(report.results).toSorted()) {
    // Every key came from `Object.keys`, so the lookup is always defined; the
    // assertion satisfies `noUncheckedIndexedAccess` without a dead guard.
    sortedResults[name] = report.results[name] as RunResult;
  }

  const canonical: Report = report.ref
    ? { recordedAt: report.recordedAt, ref: report.ref, results: sortedResults }
    : { recordedAt: report.recordedAt, results: sortedResults };

  return `${JSON.stringify(canonical, null, 2)}\n`;
}

/** Parse a previously recorded `results.json` back into its `ResultsByName` baseline. */
export function parseBaseline(json: string): ResultsByName {
  const parsed = JSON.parse(json) as Report;

  return parsed.results;
}
