/**
 * Generate a wrangler config from a deploy plan — and serialize it to the exact
 * `wrangler.jsonc` bytes that ship in the repo.
 *
 * The Cloudflare deployment of a Lesto site set is one Worker plus a Static
 * Assets binding: the Worker runs the dynamic zone(s), and the prerendered
 * static zone(s) are served from the assets directory (tried first — see
 * `withAssets`). This reads the {@link DeployPlan} to confirm there is a dynamic
 * zone for the Worker to run, then emits the `wrangler.jsonc` object that wires
 * it up: `nodejs_compat` (for `node:crypto` — the signed-session HMAC) and the
 * assets binding the Worker reaches through `env.ASSETS`. A real deploy needs
 * more than that bare pair, so {@link WranglerOptions} also carries the optional
 * knobs the estate Worker actually deploys with — module `alias`es (Preact on
 * the edge), `d1_databases` (the content store), plain `vars`, and `placement`.
 *
 * {@link wranglerConfig} is pure: it returns a plain object.
 * {@link serializeWranglerConfig} turns that object into JSONC text — tab
 * indentation, trailing commas, and caller-supplied doc comments — so the
 * committed `examples/estate/wrangler.jsonc` is reproducible from this generator
 * (its header's "Generated by `wranglerConfig`" claim is test-locked against
 * drift). `compatibility_date` is an input, never `new Date()` — a generated
 * config must be reproducible.
 */

import type { DeployPlan } from "@lesto/deploy";

import { CloudflareError } from "./errors";

/** A D1 database binding the Worker reaches through `env[binding]`. */
export interface WranglerD1Database {
  /** The binding name on `env` (e.g. `DB`). */
  readonly binding: string;

  /** The human database name (`wrangler d1 create <name>`). */
  readonly databaseName: string;

  /** The D1 database id printed by `wrangler d1 create`. */
  readonly databaseId: string;
}

/**
 * Where Cloudflare runs the Worker. `mode: "smart"` lets Cloudflare place the
 * isolate near the resources it talks to; omit for the default edge placement.
 */
export interface WranglerPlacement {
  readonly mode: "smart";
}

/** What the generator needs that the plan cannot supply — names, dates, paths. */
export interface WranglerOptions {
  /** The Worker's name. */
  readonly name: string;

  /** The Worker entry module (the file exporting `{ fetch }`). */
  readonly main: string;

  /** Pinned compatibility date — reproducible, so passed in, never derived. */
  readonly compatibilityDate: string;

  /** The directory of prerendered static files to bind as assets. */
  readonly assetsDir: string;

  /** The binding name the Worker reads assets through. Defaults to `ASSETS`. */
  readonly assetsBinding?: string;

  /**
   * Module specifier rewrites applied to the Worker bundle (e.g. resolving
   * `react` to `preact/compat` for the edge). Omitted from the output when
   * empty — a bare config carries no `alias`.
   */
  readonly alias?: Readonly<Record<string, string>>;

  /** D1 bindings the Worker reads. Omitted from the output when empty. */
  readonly d1Databases?: readonly WranglerD1Database[];

  /** Plain (non-secret) text vars exposed on `env`. Omitted when empty. */
  readonly vars?: Readonly<Record<string, string>>;

  /** Worker placement hint. Omitted from the output when absent. */
  readonly placement?: WranglerPlacement;
}

/** The `wrangler.jsonc` shape this emits — a plain object the caller serializes. */
export interface WranglerConfig {
  readonly name: string;

  readonly main: string;

  readonly compatibility_date: string;

  readonly compatibility_flags: readonly string[];

  readonly assets: {
    readonly directory: string;

    readonly binding: string;
  };

  /** Present only when {@link WranglerOptions.alias} was supplied. */
  readonly alias?: Readonly<Record<string, string>>;

  /** Present only when {@link WranglerOptions.d1Databases} was supplied. */
  readonly d1_databases?: readonly {
    readonly binding: string;
    readonly database_name: string;
    readonly database_id: string;
  }[];

  /** Present only when {@link WranglerOptions.vars} was supplied. */
  readonly vars?: Readonly<Record<string, string>>;

  /** Present only when {@link WranglerOptions.placement} was supplied. */
  readonly placement?: WranglerPlacement;
}

/**
 * Build the wrangler config for deploying a plan to Cloudflare.
 *
 * Throws `CLOUDFLARE_NO_DYNAMIC_ZONE` when the plan has no dynamic target — a
 * fully-static site needs no Worker, so generating one would be a mistake worth
 * surfacing rather than a silent empty Worker.
 *
 * Optional bindings (`alias`, `d1Databases`, `vars`, `placement`) are emitted
 * only when supplied and non-empty: a bare deploy stays a bare config.
 */
export function wranglerConfig(plan: DeployPlan, options: WranglerOptions): WranglerConfig {
  const hasDynamicZone = plan.targets.some((target) => target.kind === "node");

  if (!hasDynamicZone) {
    throw new CloudflareError(
      "CLOUDFLARE_NO_DYNAMIC_ZONE",
      "This plan has no dynamic zone, so it needs no Worker — deploy its static assets directly.",
    );
  }

  const config: WranglerConfig = {
    name: options.name,
    main: options.main,
    compatibility_date: options.compatibilityDate,
    // `nodejs_compat` gives the Worker `node:crypto`, which the signed-session
    // HMAC verification depends on at the edge.
    compatibility_flags: ["nodejs_compat"],
    assets: {
      directory: options.assetsDir,
      binding: options.assetsBinding ?? "ASSETS",
    },
  };

  return {
    ...config,
    ...(options.d1Databases && options.d1Databases.length > 0
      ? {
          d1_databases: options.d1Databases.map((db) => ({
            binding: db.binding,
            database_name: db.databaseName,
            database_id: db.databaseId,
          })),
        }
      : {}),
    ...(options.alias && Object.keys(options.alias).length > 0 ? { alias: options.alias } : {}),
    ...(options.vars && Object.keys(options.vars).length > 0 ? { vars: options.vars } : {}),
    ...(options.placement ? { placement: options.placement } : {}),
  };
}

/** Doc comments to weave into the serialized JSONC, keyed by where they go. */
export interface WranglerComments {
  /**
   * Lines emitted at the very top of the file, before the opening `{`. Each
   * string is one comment line (no `//` prefix — the serializer adds it).
   */
  readonly header?: readonly string[];

  /**
   * Lines emitted immediately above a top-level field, keyed by the field's
   * JSON name (e.g. `compatibility_flags`, `assets`, `d1_databases`, `alias`).
   * Each string is one comment line (no `//` prefix).
   */
  readonly fields?: Readonly<Record<string, readonly string[]>>;
}

const INDENT = "\t";

/** Render one comment line at `depth` (no body when the text is empty). */
function commentLine(text: string, depth: number): string {
  const prefix = INDENT.repeat(depth);

  return text.length > 0 ? `${prefix}// ${text}` : `${prefix}//`;
}

/**
 * Serialize a JSON value to JSONC lines with tab indentation and a trailing
 * comma after every array element and object property — the house style of the
 * committed `wrangler.jsonc`. Returns the lines for `value` indented at `depth`;
 * the caller joins them and appends a trailing comma where needed.
 *
 * Top-level objects route through {@link serializeWranglerConfig}, which weaves
 * in comments; this handles the comment-free nested values.
 */
function serializeValue(value: unknown, depth: number): string {
  const pad = INDENT.repeat(depth);

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[]";
    }

    const childPad = INDENT.repeat(depth + 1);
    const items = value.map((item) => `${childPad}${serializeValue(item, depth + 1)},`).join("\n");

    return `[\n${items}\n${pad}]`;
  }

  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);

    if (entries.length === 0) {
      return "{}";
    }

    const childPad = INDENT.repeat(depth + 1);
    const props = entries
      .map(
        ([key, child]) => `${childPad}${JSON.stringify(key)}: ${serializeValue(child, depth + 1)},`,
      )
      .join("\n");

    return `{\n${props}\n${pad}}`;
  }

  // Strings, numbers, booleans, null — JSON's own encoding is the JSONC encoding.
  return JSON.stringify(value);
}

/**
 * Serialize a {@link WranglerConfig} to `wrangler.jsonc` text — tab indentation,
 * a trailing comma after every element and property, and the caller's doc
 * comments woven above the header and chosen fields.
 *
 * This is the other half of the "Generated by `wranglerConfig`" promise: the
 * committed `examples/estate/wrangler.jsonc` is exactly
 * `serializeWranglerConfig(wranglerConfig(plan, options), estateComments)`, and
 * a round-trip test in this package fails CI on any drift (a `compatibility_date`
 * bump, a binding rename). The output ends with a trailing newline.
 */
export function serializeWranglerConfig(
  config: WranglerConfig,
  comments: WranglerComments = {},
): string {
  const lines: string[] = [];

  for (const text of comments.header ?? []) {
    lines.push(commentLine(text, 0));
  }

  lines.push("{");

  const fieldComments = comments.fields ?? {};

  // `wranglerConfig` omits absent optional bindings entirely (rather than
  // setting them `undefined`), so `Object.entries` only yields present fields.
  for (const [key, value] of Object.entries(config)) {
    for (const text of fieldComments[key] ?? []) {
      lines.push(commentLine(text, 1));
    }

    lines.push(`${INDENT}${JSON.stringify(key)}: ${serializeValue(value, 1)},`);
  }

  lines.push("}");

  return `${lines.join("\n")}\n`;
}
