import type { AnyCollection } from "./types";
import type { AnyTaxonomy } from "./taxonomy";
import { getTaxonomySlugs } from "./taxonomy";
import { toPascalCase, toSafeKey } from "./utils";

/**
 * Configuration for type generation.
 */
export interface TypegenConfig {
  /**
   * Relative path from output directory to the config file.
   * @example "../docks.config"
   */
  configPath?: string;
}

/**
 * Generate TypeScript types for MDX component registry.
 */
function generateMDXComponentTypes(collection: AnyCollection): string {
  const mdxConfig = collection.mdx;
  if (!mdxConfig?.components || Object.keys(mdxConfig.components).length === 0) {
    return "";
  }

  const pascalName = toPascalCase(collection.name);
  const componentEntries = Object.entries(mdxConfig.components)
    .map(([name, path]) => `  ${toSafeKey(name)}: typeof import('${path}').default;`)
    .join("\n");

  return `export interface ${pascalName}Components {\n${componentEntries}\n}\n`;
}

function generateTaxonomyTypes(taxonomies: AnyTaxonomy[]): string[] {
  if (taxonomies.length === 0) return [];

  const lines: string[] = [];
  for (const taxonomy of taxonomies) {
    const pascalName = toPascalCase(taxonomy.name);
    const slugs = getTaxonomySlugs(taxonomy);
    const unionType = slugs.length > 0 ? slugs.map((s) => JSON.stringify(s)).join(" | ") : "never";
    lines.push(`export type ${pascalName} = ${unionType};`);
  }
  return lines;
}

function generateTaxonomyRegistry(taxonomies: AnyTaxonomy[]): string[] {
  if (taxonomies.length === 0) return [];

  const lines: string[] = ["", "  interface TaxonomyRegistry {"];
  for (const taxonomy of taxonomies) {
    const slugs = getTaxonomySlugs(taxonomy);
    const slugType = slugs.length > 0 ? slugs.map((s) => JSON.stringify(s)).join(" | ") : "never";
    lines.push(`    "${taxonomy.name}": ${slugType};`);
  }
  lines.push("  }");
  return lines;
}

function generateMDXComponentTypesSection(collections: AnyCollection[]): string[] {
  const types: string[] = [];
  for (const collection of collections) {
    const componentType = generateMDXComponentTypes(collection);
    if (componentType) {
      types.push(componentType);
    }
  }
  if (types.length === 0) return [];
  return ["", "// MDX Component Types", ...types];
}

/**
 * Generate TypeScript type definitions using TypeScript inference.
 *
 * This approach works with ANY Standard Schema library (Zod, Valibot, ArkType, etc.)
 * by importing the config and using utility types to infer entry/schema types at compile time.
 *
 * @param collections - Collection configurations
 * @param taxonomies - Taxonomy configurations
 * @param config - Optional typegen configuration
 */
export function generateTypes(
  collections: AnyCollection[],
  taxonomies: AnyTaxonomy[] = [],
  config: TypegenConfig = {},
): string {
  const configPath = config.configPath ?? "../docks.config";

  const lines: string[] = [
    "// Auto-generated by @keel/content-core - DO NOT EDIT",
    "//",
    "// Types are inferred from your config using TypeScript's type system.",
    "// This works with ANY Standard Schema library (Zod, Valibot, ArkType, etc.)",
    "",
    `import type config from "${configPath}";`,
    'import type { GetEntryByName, GetSchemaByName } from "@keel/content-core";',
    "",
  ];

  // Generate type aliases using inference from config
  lines.push("// Type aliases inferred from your config");
  for (const collection of collections) {
    const pascal = toPascalCase(collection.name);
    lines.push(`export type ${pascal} = GetEntryByName<typeof config, "${collection.name}">;`);
    lines.push(
      `export type ${pascal}Schema = GetSchemaByName<typeof config, "${collection.name}">;`,
    );
  }
  lines.push("");

  // Module augmentation for CollectionRegistry (enables runtime API type safety)
  lines.push("// Module augmentation for runtime API type safety");
  lines.push('declare module "@keel/content-core" {');
  lines.push("  interface CollectionRegistry {");

  for (const collection of collections) {
    const pascal = toPascalCase(collection.name);
    lines.push(`    "${collection.name}": { entry: ${pascal}; schema: ${pascal}Schema };`);
  }

  lines.push("  }");
  lines.push(...generateTaxonomyRegistry(taxonomies));
  lines.push("}");

  // Add taxonomy types
  const taxonomyTypeLines = generateTaxonomyTypes(taxonomies);
  if (taxonomyTypeLines.length > 0) {
    lines.push("");
    lines.push(...taxonomyTypeLines);
  }

  // Add MDX component types
  lines.push(...generateMDXComponentTypesSection(collections));
  lines.push("");

  return lines.join("\n");
}

export interface GeneratedOutput {
  types: string;
  collections: string[];
  taxonomies: string[];
}

export function generate(
  collections: AnyCollection[],
  taxonomies: AnyTaxonomy[] = [],
  config: TypegenConfig = {},
): GeneratedOutput {
  return {
    types: generateTypes(collections, taxonomies, config),
    collections: collections.map((c) => c.name),
    taxonomies: taxonomies.map((t) => t.name),
  };
}
