import { describe, expect, test } from "vitest";

import { renderAgentsMd } from "../src/agents/render-agents";
import { scanConventions } from "../src/agents/scan";
import type { AgentArtifacts } from "../src/agents/types";

/** A populated, pre-scanned artifacts value (scanConventions sorts + flags). */
function artifacts(): AgentArtifacts {
  return scanConventions({
    summary: { framework: "lesto", uiDialect: "react" },
    routes: [
      { kind: "page", pattern: "/" },
      { kind: "layout", pattern: "/" },
      { kind: "page", pattern: "/blog/:slug" },
    ],
    islands: ["Counter"],
    collections: [
      { name: "posts", entryCount: 3 },
      { name: "tags", entryCount: 1 },
    ],
    commands: [
      { name: "generate", aliases: ["g"], summary: "Scaffold a resource" },
      { name: "serve", summary: "Boot the app over HTTP" },
    ],
  });
}

describe("renderAgentsMd", () => {
  test("renders every section deterministically (byte-stable snapshot)", () => {
    expect(renderAgentsMd(artifacts())).toBe(
      [
        "# Agent guide",
        "",
        "_Generated by `lesto generate agents`. Content inside the markers is overwritten on the next run; edit outside them._",
        "",
        "**Stack:** Lesto · react",
        "",
        "## Routes",
        "",
        "- `/` — layout",
        "- `/` — page",
        "- `/blog/:slug` — page",
        "",
        "## Islands",
        "",
        "- `Counter`",
        "",
        "## Content collections",
        "",
        "- `posts` — 3 entries",
        "- `tags` — 1 entry", // singular noun when entryCount === 1
        "",
        "## CLI commands",
        "",
        "- `lesto generate` (alias `g`) — Scaffold a resource",
        "- `lesto serve` — Boot the app over HTTP",
      ].join("\n"),
    );
  });

  test("omits the dialect from the stack line when uiDialect is absent", () => {
    const out = renderAgentsMd(
      scanConventions({
        summary: { framework: "lesto" },
        routes: [{ kind: "page", pattern: "/" }],
        islands: [],
        collections: [],
        commands: [],
      }),
    );

    expect(out).toContain("**Stack:** Lesto\n");
    expect(out).not.toContain("Lesto · ");
  });

  test("renders an empty section as _None._", () => {
    const out = renderAgentsMd(
      scanConventions({
        summary: { framework: "lesto" },
        routes: [{ kind: "page", pattern: "/" }],
        islands: [],
        collections: [],
        commands: [],
      }),
    );

    // Islands, collections, and commands are all empty here.
    expect(out).toContain("## Islands\n\n_None._");
    expect(out).toContain("## Content collections\n\n_None._");
    expect(out).toContain("## CLI commands\n\n_None._");
  });

  test("renders the programmatic-routing note when there are no file routes but collections exist", () => {
    // A content-driven app (the docs site): no `app/routes/` files, but it registers
    // its pages programmatically from a content collection. A bare "_None._" would be
    // misleading — the app serves a page per entry — so the Routes section explains the
    // routing model and points at the collections, without fabricating URL patterns.
    const out = renderAgentsMd(
      scanConventions({
        summary: { framework: "lesto" },
        routes: [],
        islands: [],
        collections: [{ name: "docs", entryCount: 40 }],
        commands: [],
      }),
    );

    expect(out).toContain("## Routes\n\n_No file-based routes");
    expect(out).toContain("registers its pages programmatically from its content collections");
    expect(out).toContain("see the Content collections section below");
    // The honest note REPLACES the misleading "None" in the Routes section.
    expect(out).not.toContain("## Routes\n\n_None._");
  });

  test("renders multiple aliases as a comma-separated list", () => {
    const out = renderAgentsMd(
      scanConventions({
        summary: { framework: "lesto" },
        routes: [],
        islands: ["X"],
        collections: [],
        commands: [{ name: "generate", aliases: ["g", "gen"], summary: "Scaffold" }],
      }),
    );

    expect(out).toContain("- `lesto generate` (alias `g`, `gen`) — Scaffold");
  });

  test("is byte-stable across calls", () => {
    expect(renderAgentsMd(artifacts())).toBe(renderAgentsMd(artifacts()));
  });
});
