/**
 * `lesto add <integration>` — wire a batteries-included integration into an app.
 *
 * Where `lesto g` scaffolds ONE resource (a model, a page), `lesto add` wires a
 * cross-cutting CONCERN that is several files plus a bit of composition: the
 * convention-correct, typed, commented version of a wiring the user would
 * otherwise copy out of an example and fix the imports on (ADR 0039).
 *
 *   lesto add mcp-auth          # an authenticated MCP Resource Server
 *
 * The first (and, today, only) integration is `mcp-auth`: it emits the exact
 * shape `examples/mcp-auth-openauth/mcp/` proves — a `VerifyAccessToken` adapter
 * (JWKS via `jose`), a `governance.ts` that mounts `createMcpHttpHandlers` with a
 * `createBearerAuthenticator`, a `rolesOf` stub, and a `config.ts` of the values
 * the operator must fill (issuer, resource/clientID, scopes, allowed origins) —
 * then prints the next steps. The auth values are TODO placeholders on purpose:
 * the WIRING is the battery, the issuer is config (ADR 0039), and a generated
 * file the author reads once and commits is the right place to make the config
 * holes loud rather than guess them.
 *
 * Like `runGenerate`, the core is pure and fully injected: a test hands it a fake
 * `exists`/`read`/`write` and a capturing `out` and asserts on the exact files
 * that would be written and the lines printed — no disk, no app boot. The bin
 * wires the real, project-rooted filesystem seam (the same `generateIO` `g` uses).
 *
 *   - `--dry-run` prints the plan (every path + a "would write"/"would skip"
 *     marker) and writes nothing — the safe preview before a real run.
 *   - Idempotency: a file that already exists is SKIPPED, never clobbered. Re-running
 *     after editing an emitted file is a no-op on that file, so `add` is safe to
 *     re-run (the same contract `g` keeps).
 */

import { CliError } from "./errors";
import { hasFlag } from "./flags";

/** The filesystem seam `runAdd` needs — injected so tests fake it (shared with `g`). */
export interface AddIO {
  /** True iff a path already exists (so a re-run skips rather than clobbers). */
  exists: (path: string) => Promise<boolean>;

  /** Read an existing file's contents (used to tell "unchanged" from "differs"). */
  read: (path: string) => Promise<string>;

  /** Write a file's contents, creating parent directories as needed. */
  write: (path: string, contents: string) => Promise<void>;
}

/** The seams `lesto add` depends on — all injected, never imported live. */
export interface AddDeps extends AddIO {
  /** Where a line of output goes (the bin passes `console.log`). */
  out: (line: string) => void;
}

/** A file an integration would write: its path and rendered contents. */
export interface GeneratedFile {
  readonly path: string;
  readonly contents: string;
}

/** The directory the `mcp-auth` integration writes its module into. */
const MCP_AUTH_DIR = "app/mcp";

/**
 * Render `app/mcp/config.ts` — the values an operator MUST fill, in one place.
 *
 * Every hole is a `TODO` rather than a guessed default: the issuer URL, the
 * `resource`/`clientID` the audience guard checks against, the scope vocabulary,
 * and the DNS-rebinding origin allowlist. Pulling them out of `governance.ts`
 * keeps the wiring (which the author rarely edits) apart from the config (which
 * the author always edits) — the same split `examples/mcp-auth-openauth` makes
 * between its `alchemy.run.ts` bindings and `governance.ts`.
 */
function configFile(): string {
  return `/**
 * The config holes an authenticated MCP Resource Server needs filled — generated by
 * \`lesto add mcp-auth\`. The WIRING lives in \`./governance.ts\` and rarely changes;
 * the VALUES live here and are yours to fill. Each TODO is a deliberate hole, not a
 * guessed default (ADR 0039).
 */

/** The OAuth scope vocabulary. \`write\` is the ceiling that unlocks the destructive tools. */
export const SCOPES = { read: "mcp:read", write: "mcp:write" } as const;

/** The issuer-and-policy values the governed app reads. Fill every TODO before deploying. */
export interface McpAuthConfig {
  /** The Authorization Server's issuer identifier (\`iss\`) — your IdP's URL. */
  issuer: string;

  /** The issuer's \`jwks_uri\` — where the RS fetches the signing keys to verify tokens. */
  jwksUrl: URL;

  /**
   * This RS's canonical resource identifier — the audience tokens MUST carry. The
   * battery's confused-deputy guard refuses any token whose \`aud\` is not exactly this,
   * so a token a user granted to a DIFFERENT resource cannot be replayed here. Set it to
   * the value your issuer stamps into \`aud\` (with an OAuth client-credentials IdP that
   * does not implement RFC 8707 resource indicators, that is the client id).
   */
  resource: string;

  /** This RS's public base URL — the RFC 9728 \`resource_metadata\` pointer derives from it. */
  baseUrl: string;

  /** The browser origins allowed to reach the server (the DNS-rebinding allowlist). */
  allowedOrigins: readonly string[];
}

/**
 * Fill these in. They are TODO placeholders so a forgotten value fails LOUD (a wrong
 * issuer 401s every token; a wrong \`resource\` refuses every token) rather than silently
 * trusting the wrong authority.
 */
export const mcpAuthConfig: McpAuthConfig = {
  // TODO: your issuer's URL, e.g. "https://auth.example.com" or an Auth0/Okta tenant.
  issuer: "https://issuer.example.com",

  // TODO: the issuer's JWKS endpoint (from its /.well-known discovery document).
  jwksUrl: new URL("https://issuer.example.com/.well-known/jwks.json"),

  // TODO: the audience your issuer mints into \`aud\` for THIS server.
  resource: "https://mcp.example.com",

  // TODO: this server's own public base URL (used only for the metadata pointer).
  baseUrl: "https://mcp.example.com",

  // Agents and curl send no Origin (no DNS-rebinding risk → allowed); a browser's
  // cross-site Origin is refused. Add the browser origins you trust, or leave empty.
  allowedOrigins: [],
};
`;
}

/**
 * Render `app/mcp/verify.ts` — the one issuer-specific seam: a `VerifyAccessToken`
 * that validates a JWT against the issuer's JWKS with `jose`.
 *
 * This is the SINGLE file an operator edits to change issuers — the battery
 * (`governance.ts`) is issuer-agnostic. The stub pins the common case (RS256, the
 * default for Auth0/Okta/most OIDC IdPs) and maps the standard `sub`/`aud`/`scope`
 * claims onto the RS contract; a bad token is `undefined` (a 401), never a throw.
 * The mapping is the EXACT place to adapt a non-standard issuer (e.g. one that
 * carries scopes in a custom claim), with a pointer to the OpenAuth example.
 */
function verifyFile(): string {
  return `/**
 * The \`VerifyAccessToken\` seam — the ONLY issuer-specific code in an authenticated MCP
 * Resource Server. Generated by \`lesto add mcp-auth\`.
 *
 * The \`@lesto/mcp\` governance is issuer-agnostic: it asks this adapter "is this bearer
 * token valid, and for whom?" and enforces audience + scope + role on the answer. So
 * pointing the RS at Auth0, Okta, or your own issuer is a change to THIS file alone — the
 * battery in \`./governance.ts\` never moves. (See examples/mcp-auth-openauth/mcp/verify.ts
 * for an OpenAuth issuer whose scopes ride in a non-standard \`properties\` claim.)
 *
 * Verification is standard + offline: fetch + cache the issuer's JWKS, then check the
 * signature, issuer, and expiry. A malformed / forged / expired / wrong-issuer token maps
 * to \`undefined\` — the RS turns that into a 401, never a throw.
 */

import { createRemoteJWKSet, jwtVerify } from "jose";

import type { AccessTokenClaims, VerifyAccessToken } from "@lesto/mcp";

import { mcpAuthConfig } from "./config";

// The issuer's signing keys, fetched once and cached (jose handles reload + cooldown).
const keys = createRemoteJWKSet(mcpAuthConfig.jwksUrl);

/**
 * Validate a bearer token and project it onto the RS contract
 * (\`{ subject, audience, scopes }\`). Returns the claims on a valid token from the
 * configured issuer, or \`undefined\` for anything the RS should refuse with a 401.
 */
export const verifyAccessToken: VerifyAccessToken = async (
  token: string,
): Promise<AccessTokenClaims | undefined> => {
  try {
    // TODO: pin your issuer's signing algorithm. RS256 is the OIDC default (Auth0/Okta);
    // some issuers (e.g. OpenAuth) sign ES256 — set \`algorithms\` to match, or a valid
    // token is rejected.
    const { payload } = await jwtVerify(token, keys, {
      issuer: mcpAuthConfig.issuer,
      algorithms: ["RS256"],
    });

    // The subject is the principal the RS attributes + audits. Standard OIDC carries it
    // in \`sub\`; adapt this if your issuer puts the user id elsewhere.
    if (typeof payload.sub !== "string") return undefined;

    // The OAuth \`scope\` claim is a space-delimited string (RFC 8693). An issuer that has
    // no \`scope\` claim (e.g. scopes in a custom array claim) needs this mapping adapted.
    const scope = typeof payload.scope === "string" ? payload.scope : "";

    return {
      subject: payload.sub,
      // \`aud\` is who the token was minted FOR; the battery refuses any token whose \`aud\`
      // is not \`mcpAuthConfig.resource\` (the confused-deputy guard).
      audience: payload.aud ?? [],
      scopes: scope.split(" ").filter((s) => s.length > 0),
    };
  } catch {
    // Any verification failure (bad signature, wrong issuer, expired) is a 401, not a 500.
    return undefined;
  }
};
`;
}

/**
 * Render `app/mcp/governance.ts` — the battery wiring, UNCHANGED across issuers.
 *
 * Builds a `@lesto/web` sub-app, mounts the RFC 9728 PRM + the Streamable-HTTP MCP
 * endpoint via `createMcpHttpHandlers`, and authenticates each request with a
 * `createBearerAuthenticator` (the audience guard + the `rolesOf` subject→roles
 * bind). This is the exact composition `examples/mcp-auth-openauth/mcp/governance.ts`
 * proves; the only things it reads from outside are the `verifyAccessToken` seam and
 * the `config`. The user mounts the returned app onto their own `lesto.app.ts`.
 */
function governanceFile(): string {
  return `/**
 * The \`@lesto/mcp\` Resource Server governance — the battery, wired ONCE and unchanged
 * across issuers. Generated by \`lesto add mcp-auth\`.
 *
 * \`createBearerAuthenticator\` → \`createMcpHttpHandlers\` is the whole wedge (ADR 0039): a
 * token is validated by the issuer-specific \`./verify.ts\` seam, then the battery enforces
 * the audience (no confused-deputy passthrough), the scope ceiling (a viewer can read but
 * not write), the DNS-rebinding origin allowlist, and binds the subject to a principal via
 * \`rolesOf\`. Every authenticated tool call lands on the audit trail.
 *
 * Mount the returned app onto your \`lesto.app.ts\`, or serve it directly. On Node it boots
 * on the kernel; on the edge \`@lesto/cloudflare\`'s \`toFetchHandler\` runs the SAME app —
 * the governance is byte-identical across substrates (see the example's worker.ts).
 */

import type { App } from "@lesto/kernel";
import { createBearerAuthenticator, createMcpHttpHandlers } from "@lesto/mcp";
import type { McpAuditRecord } from "@lesto/mcp";
import { lesto } from "@lesto/web";
import type { Lesto } from "@lesto/web";

import { mcpAuthConfig, SCOPES } from "./config";
import { verifyAccessToken } from "./verify";

/** The governed app plus the audit trail it closes over. */
export interface GovernedMcp {
  /** The transport-neutral \`@lesto/web\` app — mount it onto your \`lesto.app.ts\`. */
  api: Lesto;

  /** The MCP audit trail (every authenticated tool call lands here). */
  audit: McpAuditRecord[];
}

/**
 * Resolve a subject's roles — recorded on the principal and the audit, and read by the
 * per-tool policy floor (OCP-7). This is a STUB: wire it to your real user store.
 *
 * The default below is deliberately conservative — an unknown subject is a \`viewer\`
 * (read-only), and only an explicit allowlist earns \`operator\` (the destructive tools).
 * Replace the body with a lookup against your users/roles table.
 */
export function rolesOf(subject: string): string[] {
  // TODO: look the subject's roles up in your store. The allowlist here is a placeholder.
  const operators = new Set<string>([
    // "operator@example.com",
  ]);

  return operators.has(subject) ? ["operator"] : ["viewer"];
}

/**
 * Build the governed MCP Resource Server on a fresh \`@lesto/web\` app.
 *
 * \`app\` is the booted {@link App} the MCP tools dispatch back INTO — \`handle_request\`
 * drives a real request through your live app. It is read only at REQUEST time, so a Node
 * server passes a forward-reference to the app it boots AFTER this returns; an edge Worker
 * (no kernel) omits it and the tools self-dispatch into \`api\`.
 */
export function buildGovernedMcp(app?: App): GovernedMcp {
  const audit: McpAuditRecord[] = [];

  // Your app's MCP surface. \`list_routes\` is read-only; \`handle_request\` is destructive
  // (it drives a real request), so the \`mcp:write\` scope ceiling gates it. Replace this
  // health route with whatever the MCP tools should be able to reach.
  const api = lesto().get("/health", (c) => c.json({ ok: true }));

  // Captured BEFORE the MCP routes are mounted, so \`list_routes\` reports YOUR app's
  // routes, not the MCP plumbing.
  const routes = api.routes();

  // With no kernel app (the edge), MCP tool dispatch falls back into this very \`api\`.
  const contextApp: App = app ?? {
    handle: (method, path, requestOptions) => api.handle(method, path, requestOptions),
    migrationsApplied: [],
  };

  const resourceMetadataUrl = \`\${mcpAuthConfig.baseUrl}/.well-known/oauth-protected-resource\`;

  const handlers = createMcpHttpHandlers({
    context: {
      app: contextApp,
      routes,
      audit: (record) => {
        audit.push(record);
      },
    },
    // The ONLY issuer-specific wiring: validate a real token via \`./verify.ts\`, bind its
    // subject to a principal via \`rolesOf\`, and refuse any token not audienced to us.
    authenticate: createBearerAuthenticator({
      verifyAccessToken,
      resource: mcpAuthConfig.resource,
      rolesOf,
    }),
    resource: mcpAuthConfig.resource,
    authorizationServers: [mcpAuthConfig.issuer],
    scopesSupported: [SCOPES.read, SCOPES.write],
    writeScope: SCOPES.write,
    allowedOrigins: mcpAuthConfig.allowedOrigins,
    resourceMetadataUrl,
  });

  // The RFC 9728 PRM a client reads to discover where to get a token; the MCP endpoint a
  // client POSTs to; and a 405 on GET so an SSE probe gets a clean answer.
  api
    .get("/.well-known/oauth-protected-resource", handlers.metadata)
    .post("/mcp", handlers.rpc)
    .get("/mcp", () => ({ status: 405, headers: { allow: "POST" }, body: "" }));

  return { api, audit };
}
`;
}

/** The next-steps lines printed after a successful `mcp-auth` scaffold. */
const MCP_AUTH_NEXT_STEPS: readonly string[] = [
  "",
  "Next steps:",
  `  1. Fill in the TODOs in ${MCP_AUTH_DIR}/config.ts (issuer, jwksUrl, resource, baseUrl).`,
  `  2. Adjust ${MCP_AUTH_DIR}/verify.ts for your issuer's signing alg + claim shape (RS256 by default).`,
  `  3. Wire rolesOf in ${MCP_AUTH_DIR}/governance.ts to your real user store.`,
  `  4. Mount the governed app: import { buildGovernedMcp } from "./${MCP_AUTH_DIR}/governance"`,
  "     and compose its `.api` onto your lesto.app.ts (or serve it directly).",
  "  5. Add the `jose` dependency: `bun add jose`.",
  "",
  "See examples/mcp-auth-openauth for a full, runnable issuer + RS + agent.",
];

/** Plan the `mcp-auth` integration's files (config, the verifier seam, the battery wiring). */
function planMcpAuth(): GeneratedFile[] {
  return [
    { path: `${MCP_AUTH_DIR}/config.ts`, contents: configFile() },
    { path: `${MCP_AUTH_DIR}/verify.ts`, contents: verifyFile() },
    { path: `${MCP_AUTH_DIR}/governance.ts`, contents: governanceFile() },
  ];
}

/** The integrations `lesto add` implements today. */
const INTEGRATIONS = ["mcp-auth"] as const;

type Integration = (typeof INTEGRATIONS)[number];

/** The next-steps block each integration prints after its files are written. */
const NEXT_STEPS: Readonly<Record<Integration, readonly string[]>> = {
  "mcp-auth": MCP_AUTH_NEXT_STEPS,
};

/** True iff `value` names an integration this CLI implements today. */
function isIntegration(value: string | undefined): value is Integration {
  return value !== undefined && (INTEGRATIONS as readonly string[]).includes(value);
}

/**
 * Run a `lesto add <integration>` invocation.
 *
 * Validates the integration name up front — a missing or unknown name is refused by a
 * stable code before a single file is touched. Then, for each planned file, the SAME
 * idempotent write contract `g` keeps:
 *
 *   - `--dry-run`: print `would write <path>` (or `would skip <path>` for a path that
 *     already exists) and write nothing.
 *   - an existing file: print `exists <path> (unchanged)` if byte-identical, or
 *     `exists <path> (differs — left unchanged; edit or delete to regenerate)` if not —
 *     then SKIP it (never clobbered).
 *   - otherwise: write it and print `wrote <path>`.
 *
 * After a real run, the integration's next-steps are printed so the operator knows
 * exactly which TODOs to fill. Returns the process exit code (0 on a successful plan; a
 * refusal throws a coded {@link CliError} the caller turns into a non-zero exit).
 */
export async function runAdd(args: readonly string[], deps: AddDeps): Promise<number> {
  const [integration] = args;

  if (integration === undefined) {
    throw new CliError(
      "CLI_ADD_MISSING_INTEGRATION",
      `add needs an integration: lesto add <${INTEGRATIONS.join("|")}>`,
      {},
    );
  }

  if (!isIntegration(integration)) {
    throw new CliError(
      "CLI_ADD_UNKNOWN_INTEGRATION",
      `"${integration}" is not a known integration. Available: ${INTEGRATIONS.join(", ")}.`,
      { integration, known: [...INTEGRATIONS] },
    );
  }

  const dryRun = hasFlag(args, "dry-run");
  const files = planMcpAuth();

  for (const file of files) {
    if (dryRun) {
      // A dry run reports the REAL plan: an existing path would be skipped on a real run.
      deps.out(`would ${(await deps.exists(file.path)) ? "skip" : "write"} ${file.path}`);

      continue;
    }

    // Idempotency: an existing file is left exactly as it is — safe to re-run after the
    // author has edited what it first emitted. The message distinguishes a byte-identical
    // file (a true no-op) from one whose contents differ, so a re-run is never a silent
    // data-loss surprise.
    if (await deps.exists(file.path)) {
      const current = await deps.read(file.path);

      deps.out(
        current === file.contents
          ? `exists ${file.path} (unchanged)`
          : `exists ${file.path} (differs — left unchanged; edit or delete to regenerate)`,
      );

      continue;
    }

    await deps.write(file.path, file.contents);

    deps.out(`wrote ${file.path}`);
  }

  // The next steps are printed on a real run only — a dry run wrote nothing, so there is
  // nothing yet to configure or mount.
  if (!dryRun) for (const line of NEXT_STEPS[integration]) deps.out(line);

  return 0;
}
