/**
 * @keel/router — a RESTful router, ported from the Tracks router.
 *
 * Routes map an HTTP method + path to a `controller#action` target. Paths may
 * carry `:param` segments, which match a single path segment and are extracted
 * into a params bag. Named routes can be turned back into concrete paths with
 * `pathFor`, so links never hardcode a URL.
 */

import { RouterError } from "./errors";

/** One resolved route: its verb, the path pattern it answers, and where it dispatches. */
export interface RouteInfo {
  method: string;

  pattern: string;

  target: string;

  /** The route's name, if it was declared with `as` or generated by `resources`. */
  name?: string;
}

/** What a successful `resolve` hands back: the target to dispatch and the extracted params. */
export interface Resolution {
  target: string;

  params: Record<string, string>;
}

/** Options accepted by the verb helpers (`get`, `post`, …). */
export interface RouteOptions {
  /** A stable name for the route, usable with `pathFor`. */
  as?: string;
}

/** A compiled route. The RegExp and param names are derived once, at declaration time. */
interface CompiledRoute {
  method: string;

  pattern: string;

  target: string;

  name: string | undefined;

  regExp: RegExp;

  /** The `:param` names, in the order they appear in the pattern. */
  paramNames: ReadonlyArray<string>;
}

// A `:param` segment names a capture; it matches one path segment (anything but "/").
const PARAM_SEGMENT = /:([A-Za-z_][A-Za-z0-9_]*)/g;

// Characters that are literal in a path but special in a RegExp — escaped so a
// static segment like "/posts.json" never acts as a wildcard.
const REGEXP_SPECIALS = /[.*+?^${}()|[\]\\]/g;

const escapeRegExp = (literal: string): string => literal.replace(REGEXP_SPECIALS, "\\$&");

// Strip one trailing "s" to singularize. Deliberately tiny: "posts" -> "post".
// A word without a trailing "s" is left untouched.
const singularize = (word: string): string => (word.endsWith("s") ? word.slice(0, -1) : word);

/**
 * Compile a path pattern into a RegExp plus the ordered list of its param names.
 *
 * Static parts are escaped so they match literally; each `:param` becomes a
 * `[^/]+` capture group. The pattern is anchored end-to-end.
 *
 * Refuses a pattern that puts two params in one segment (`/:a-:b`): that compiles
 * to adjacent `([^/]+)` groups separated by a literal, an ambiguous pattern whose
 * backtracking is catastrophic on a long non-matching segment — the same ReDoS
 * shape that bit `path-to-regexp` (CVE-2024-45296). And the request-handler
 * deadline is no defense: a synchronous regex blocks the event loop, so its timer
 * never fires. So we reject the shape at *declaration* time (fail fast, once)
 * rather than risk it at request time.
 */
const compile = (pattern: string): { regExp: RegExp; paramNames: ReadonlyArray<string> } => {
  const paramNames: string[] = [];

  let source = "";
  let lastIndex = 0;
  let sawParam = false;

  for (const match of pattern.matchAll(PARAM_SEGMENT)) {
    // The static text between the previous param and this one is matched literally.
    const between = pattern.slice(lastIndex, match.index);

    // No `/` since the previous param means this one shares its segment — two
    // `[^/]+` captures in one segment, the ambiguous backtracking shape we refuse.
    if (sawParam && !between.includes("/")) {
      throw new RouterError(
        "ROUTER_AMBIGUOUS_SEGMENT",
        `Route "${pattern}" puts two params in one segment (":${match[1]}" shares a segment with the param before it). Give each param its own "/" segment, or capture one param and split the value in the handler.`,
        { pattern, param: match[1] },
      );
    }

    source += escapeRegExp(between);
    source += "([^/]+)";

    // `match[1]` is the captured name; the regex guarantees it is present.
    paramNames.push(match[1] as string);

    lastIndex = match.index + match[0].length;
    sawParam = true;
  }

  // Whatever trails the final param is also literal.
  source += escapeRegExp(pattern.slice(lastIndex));

  return { regExp: new RegExp(`^${source}$`), paramNames };
};

export class Router {
  // Insertion order is the resolution order: the first matching route wins.
  private readonly routes: CompiledRoute[] = [];

  // A prefix applied to every path declared on this router, used to nest resources.
  private readonly prefix: string;

  constructor(prefix = "") {
    this.prefix = prefix;
  }

  private add(method: string, path: string, target: string, name: string | undefined): this {
    const pattern = this.prefix + path;

    const { regExp, paramNames } = compile(pattern);

    this.routes.push({ method, pattern, target, name, regExp, paramNames });

    return this;
  }

  get(path: string, target: string, options?: RouteOptions): this {
    return this.add("GET", path, target, options?.as);
  }

  post(path: string, target: string, options?: RouteOptions): this {
    return this.add("POST", path, target, options?.as);
  }

  patch(path: string, target: string, options?: RouteOptions): this {
    return this.add("PATCH", path, target, options?.as);
  }

  put(path: string, target: string, options?: RouteOptions): this {
    return this.add("PUT", path, target, options?.as);
  }

  delete(path: string, target: string, options?: RouteOptions): this {
    return this.add("DELETE", path, target, options?.as);
  }

  /** The root route: `GET "/"`, named `root`. */
  root(target: string): this {
    return this.get("/", target, { as: "root" });
  }

  /**
   * Generate the seven RESTful routes for a collection.
   *
   * When `nest` is given, child resources are declared under `/<name>/:<singular>_id`,
   * so a comment under a post resolves with `post_id` rather than a bare `id`.
   */
  resources(name: string, nest?: (router: Router) => void): this {
    const singular = singularize(name);

    this.get(`/${name}`, `${name}#index`, { as: name });
    this.get(`/${name}/new`, `${name}#new`, { as: `new_${singular}` });
    this.post(`/${name}`, `${name}#create`);
    this.get(`/${name}/:id`, `${name}#show`, { as: singular });
    this.get(`/${name}/:id/edit`, `${name}#edit`, { as: `edit_${singular}` });
    this.patch(`/${name}/:id`, `${name}#update`);
    this.put(`/${name}/:id`, `${name}#update`);
    this.delete(`/${name}/:id`, `${name}#destroy`);

    if (nest === undefined) return this;

    // Children hang off a single member: the parent's `:id` becomes `:<singular>_id`.
    const nested = new Router(`${this.prefix}/${name}/:${singular}_id`);

    nest(nested);

    for (const route of nested.routes) {
      this.routes.push(route);
    }

    return this;
  }

  /**
   * Find the route that answers this method + path.
   *
   * Returns the target and extracted params, or `undefined` when nothing matches —
   * either no pattern fits the path, or the matching pattern wants a different verb.
   */
  resolve(method: string, path: string): Resolution | undefined {
    for (const route of this.routes) {
      if (route.method !== method) continue;

      const match = route.regExp.exec(path);

      if (match === null) continue;

      const params: Record<string, string> = {};

      route.paramNames.forEach((paramName, index) => {
        // Group 0 is the whole match; captures start at 1, aligned with `paramNames`.
        params[paramName] = match[index + 1] as string;
      });

      return { target: route.target, params };
    }

    return undefined;
  }

  /**
   * Build the concrete path for a named route, substituting and URL-encoding params.
   *
   * Throws `ROUTER_UNKNOWN_NAMED_ROUTE` if no route carries the name, and
   * `ROUTER_MISSING_PARAM` if the pattern needs a param the caller did not supply.
   */
  pathFor(name: string, params: Record<string, string | number> = {}): string {
    const route = this.routes.find((candidate) => candidate.name === name);

    if (route === undefined) {
      throw new RouterError("ROUTER_UNKNOWN_NAMED_ROUTE", `No route is named "${name}".`, { name });
    }

    return route.pattern.replace(PARAM_SEGMENT, (_segment, paramName: string) => {
      const value = params[paramName];

      if (value === undefined) {
        throw new RouterError(
          "ROUTER_MISSING_PARAM",
          `Route "${name}" needs a "${paramName}" param.`,
          { name, param: paramName },
        );
      }

      return encodeURIComponent(String(value));
    });
  }

  /** Every declared route, in resolution order, for inspection and debugging. */
  list(): RouteInfo[] {
    return this.routes.map((route) => ({
      method: route.method,
      pattern: route.pattern,
      target: route.target,
      ...(route.name === undefined ? {} : { name: route.name }),
    }));
  }
}
