/**
 * @keel/router — a RESTful router, ported from the Tracks router.
 *
 * Routes map an HTTP method + path to a `controller#action` target. Paths may
 * carry `:param` segments, which match a single path segment and are extracted
 * into a params bag. Named routes can be turned back into concrete paths with
 * `pathFor`, so links never hardcode a URL.
 */

import { compile, PARAM_SEGMENT } from "./compile";
import { RouterError } from "./errors";

/** One resolved route: its verb, the path pattern it answers, and where it dispatches. */
export interface RouteInfo {
  method: string;

  pattern: string;

  target: string;

  /** The route's name, if it was declared with `as` or generated by `resources`. */
  name?: string;
}

/** What a successful `resolve` hands back: the target to dispatch and the extracted params. */
export interface Resolution {
  target: string;

  params: Record<string, string>;
}

/** Options accepted by the verb helpers (`get`, `post`, …). */
export interface RouteOptions {
  /** A stable name for the route, usable with `pathFor`. */
  as?: string;
}

/** A compiled route. The RegExp and param names are derived once, at declaration time. */
interface CompiledRoute {
  method: string;

  pattern: string;

  target: string;

  name: string | undefined;

  regExp: RegExp;

  /** The `:param` names, in the order they appear in the pattern. */
  paramNames: ReadonlyArray<string>;
}

// Strip one trailing "s" to singularize. Deliberately tiny: "posts" -> "post".
// A word without a trailing "s" is left untouched.
const singularize = (word: string): string => (word.endsWith("s") ? word.slice(0, -1) : word);

export class Router {
  // Insertion order is the resolution order: the first matching route wins.
  private readonly routes: CompiledRoute[] = [];

  // A prefix applied to every path declared on this router, used to nest resources.
  private readonly prefix: string;

  constructor(prefix = "") {
    this.prefix = prefix;
  }

  private add(method: string, path: string, target: string, name: string | undefined): this {
    const pattern = this.prefix + path;

    const { regExp, paramNames } = compile(pattern);

    this.routes.push({ method, pattern, target, name, regExp, paramNames });

    return this;
  }

  get(path: string, target: string, options?: RouteOptions): this {
    return this.add("GET", path, target, options?.as);
  }

  post(path: string, target: string, options?: RouteOptions): this {
    return this.add("POST", path, target, options?.as);
  }

  patch(path: string, target: string, options?: RouteOptions): this {
    return this.add("PATCH", path, target, options?.as);
  }

  put(path: string, target: string, options?: RouteOptions): this {
    return this.add("PUT", path, target, options?.as);
  }

  delete(path: string, target: string, options?: RouteOptions): this {
    return this.add("DELETE", path, target, options?.as);
  }

  /** The root route: `GET "/"`, named `root`. */
  root(target: string): this {
    return this.get("/", target, { as: "root" });
  }

  /**
   * Generate the seven RESTful routes for a collection.
   *
   * When `nest` is given, child resources are declared under `/<name>/:<singular>_id`,
   * so a comment under a post resolves with `post_id` rather than a bare `id`.
   */
  resources(name: string, nest?: (router: Router) => void): this {
    const singular = singularize(name);

    this.get(`/${name}`, `${name}#index`, { as: name });
    this.get(`/${name}/new`, `${name}#new`, { as: `new_${singular}` });
    this.post(`/${name}`, `${name}#create`);
    this.get(`/${name}/:id`, `${name}#show`, { as: singular });
    this.get(`/${name}/:id/edit`, `${name}#edit`, { as: `edit_${singular}` });
    this.patch(`/${name}/:id`, `${name}#update`);
    this.put(`/${name}/:id`, `${name}#update`);
    this.delete(`/${name}/:id`, `${name}#destroy`);

    if (nest === undefined) return this;

    // Children hang off a single member: the parent's `:id` becomes `:<singular>_id`.
    const nested = new Router(`${this.prefix}/${name}/:${singular}_id`);

    nest(nested);

    for (const route of nested.routes) {
      this.routes.push(route);
    }

    return this;
  }

  /**
   * Find the route that answers this method + path.
   *
   * Returns the target and extracted params, or `undefined` when nothing matches —
   * either no pattern fits the path, or the matching pattern wants a different verb.
   */
  resolve(method: string, path: string): Resolution | undefined {
    for (const route of this.routes) {
      if (route.method !== method) continue;

      const match = route.regExp.exec(path);

      if (match === null) continue;

      const params: Record<string, string> = {};

      route.paramNames.forEach((paramName, index) => {
        // Group 0 is the whole match; captures start at 1, aligned with `paramNames`.
        params[paramName] = match[index + 1] as string;
      });

      return { target: route.target, params };
    }

    return undefined;
  }

  /**
   * Build the concrete path for a named route, substituting and URL-encoding params.
   *
   * Throws `ROUTER_UNKNOWN_NAMED_ROUTE` if no route carries the name, and
   * `ROUTER_MISSING_PARAM` if the pattern needs a param the caller did not supply.
   */
  pathFor(name: string, params: Record<string, string | number> = {}): string {
    const route = this.routes.find((candidate) => candidate.name === name);

    if (route === undefined) {
      throw new RouterError("ROUTER_UNKNOWN_NAMED_ROUTE", `No route is named "${name}".`, { name });
    }

    return route.pattern.replace(PARAM_SEGMENT, (_segment, paramName: string) => {
      const value = params[paramName];

      if (value === undefined) {
        throw new RouterError(
          "ROUTER_MISSING_PARAM",
          `Route "${name}" needs a "${paramName}" param.`,
          { name, param: paramName },
        );
      }

      return encodeURIComponent(String(value));
    });
  }

  /** Every declared route, in resolution order, for inspection and debugging. */
  list(): RouteInfo[] {
    return this.routes.map((route) => ({
      method: route.method,
      pattern: route.pattern,
      target: route.target,
      ...(route.name === undefined ? {} : { name: route.name }),
    }));
  }
}
