/**
 * Render the `AGENTS.md` managed region from the convention scan.
 *
 * `AGENTS.md` is the emerging cross-agent convention (Claude Code, Cursor, …): a
 * Markdown brief an agent reads to learn how to work in THIS app. {@link renderAgentsMd}
 * turns the scan's {@link AgentArtifacts} into that brief — the routes in force, the
 * interactive islands, the content collections, and the `lesto` CLI surface — as a
 * pure function: same artifacts in, byte-identical Markdown out (the scan already
 * sorted everything by code point), so the `--check` drift guard is meaningful.
 *
 * It returns ONLY the inner content; {@link mergeManagedRegion} wraps it in the
 * markers and merges it into any author-written prose. No `fs`, no `process`.
 */

import type {
  AgentArtifacts,
  CliCommandDescriptor,
  CollectionDescriptor,
  RouteDescriptor,
} from "./types";

/** A bullet for one route — its URL pattern and convention kind. */
function routeLine(route: RouteDescriptor): string {
  return `- \`${route.pattern}\` — ${route.kind}`;
}

/** A bullet for one collection — its name and entry count, pluralized. */
function collectionLine(collection: CollectionDescriptor): string {
  const noun = collection.entryCount === 1 ? "entry" : "entries";

  return `- \`${collection.name}\` — ${collection.entryCount} ${noun}`;
}

/** A bullet for one CLI command — `lesto <name>`, any aliases, and its summary. */
function commandLine(command: CliCommandDescriptor): string {
  const aliases =
    command.aliases !== undefined && command.aliases.length > 0
      ? ` (alias ${command.aliases.map((a) => `\`${a}\``).join(", ")})`
      : "";

  return `- \`lesto ${command.name}\`${aliases} — ${command.summary}`;
}

/** Render one `## heading` section over `items`, or an italic "None." when empty. */
function section(heading: string, items: readonly string[]): string {
  const body = items.length > 0 ? items.join("\n") : "_None._";

  return `## ${heading}\n\n${body}`;
}

/**
 * Render the `AGENTS.md` managed-region content (the inner block, no markers) from
 * the scanned conventions. Deterministic and byte-stable for a given
 * {@link AgentArtifacts}.
 */
export function renderAgentsMd(artifacts: AgentArtifacts): string {
  const stack =
    artifacts.summary.uiDialect === undefined ? "Lesto" : `Lesto · ${artifacts.summary.uiDialect}`;

  return [
    "# Agent guide",
    "",
    "_Generated by `lesto generate agents`. Content inside the markers is overwritten on the next run; edit outside them._",
    "",
    `**Stack:** ${stack}`,
    "",
    section("Routes", artifacts.routes.map(routeLine)),
    "",
    section(
      "Islands",
      artifacts.islands.map((name) => `- \`${name}\``),
    ),
    "",
    section("Content collections", artifacts.collections.map(collectionLine)),
    "",
    section("CLI commands", artifacts.commands.map(commandLine)),
  ].join("\n");
}
