/**
 * The starter's files, as pure functions of the project name.
 *
 * Each function returns one file's contents as a string. They are
 * deliberately pure and side-effect free: `scaffold` owns all I/O, these
 * own all content, so the generated bytes are tested directly without
 * touching a disk.
 *
 * The app they emit is small but REAL — it boots on `@lesto/kernel`'s
 * `createApp` with a `posts` table (defined as a `@lesto/db` value), a
 * migration that runs `createTableSql(posts)`, and a code-first `lesto()`
 * app whose handlers query via `@lesto/db`. Mirrors the shape of the
 * canonical blog example (`examples/blog`) and the rest of the
 * post-ADR-0004 codebase.
 */

/**
 * The `@lesto/*` packages a scaffolded app depends on, by directory name under
 * `packages/`.
 *
 * `@lesto/cli` is the `lesto` binary `lesto dev`/`build` runs (its absence was a
 * silent break — blocker #9); `@lesto/assets` is the client-bundle pipeline the
 * island build needs in the app's graph; `@lesto/cloudflare` is the edge adapter
 * the deploy template's `worker.ts` fronts the app with (`lesto deploy
 * --cloudflare`). The rest are the app's own runtime (db/kernel/migrate/runtime,
 * the web router, the UI engine).
 */
export const LESTO_PACKAGES = [
  "@lesto/cli",
  "@lesto/assets",
  "@lesto/cloudflare",
  "@lesto/db",
  "@lesto/kernel",
  "@lesto/migrate",
  "@lesto/runtime",
  "@lesto/ui",
  "@lesto/web",
] as const;

/**
 * Resolve a `@lesto/*` package name to the dependency specifier the scaffold pins
 * it at.
 *
 * Two implementations live in `scaffold.ts`: `publishedRangePin` (the default — a
 * published `^0.x` range an outsider installs from the registry) and
 * `fileColonPin` (a `file:` path at the in-repo package, selected by
 * `create-lesto --local` for in-monorepo dev before anything is published). The
 * resolver is injected so a test can pin to a fake specifier and the publish
 * decision lives in exactly one place.
 */
export type LestoDepResolver = (pkg: (typeof LESTO_PACKAGES)[number]) => string;

/**
 * `package.json` for the scaffolded app: starter deps + a `lesto dev` script.
 *
 * The `@lesto/*` specifiers come from the injected `lestoDep` resolver (a `file:`
 * pin today; a published range post-launch), keeping this a pure function of its
 * inputs. The app ships `preact` (the ~10 KB island client the Preact dialect
 * aliases `react` to) AND `react`/`react-dom` (the server still renders React —
 * see `lesto.app.ts`'s `ui: { dialect: "preact" }`).
 */
export function packageJson(name: string, lestoDep: LestoDepResolver): string {
  const lestoDeps = Object.fromEntries(LESTO_PACKAGES.map((pkg) => [pkg, lestoDep(pkg)]));

  const manifest = {
    name,
    version: "0.0.0",
    type: "module",
    private: true,
    // A scaffolded app is the user's own private project, not a Lesto package — so
    // it declares `UNLICENSED` rather than inheriting Lesto's MIT. The author
    // changes this to whatever license their project ships under.
    license: "UNLICENSED",

    scripts: {
      dev: "lesto dev",
      build: "lesto build",
    },

    dependencies: {
      ...lestoDeps,
      "better-sqlite3": "^11.10.0",
      // The Preact dialect (`ui.dialect: "preact"`) renders BOTH halves through
      // Preact: `preact` aliases the island client's `react` to `preact/compat` for
      // the ~10 KB bundle, and `preact-render-to-string` is the SERVER renderer
      // `@lesto/web` loads for that dialect (`@lesto/ui` marks it an optional peer,
      // so the app that picks the dialect must supply it). `react`/`react-dom` remain
      // for the JSX runtime the page components compile against.
      preact: "^10.29.2",
      "preact-render-to-string": "^6",
      react: "^19",
      "react-dom": "^19",
      zod: "^4.0.0",
    },
  };

  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/**
 * `lesto.app.ts` — the project root's entrypoint.
 *
 * It default-exports a `LestoAppConfig` (the `{ db, app, migrations }` object
 * `createApp` accepts), which `@lesto/cli`'s `lesto dev` loads and boots.
 */
export function lestoApp(): string {
  return `/**
 * The app: a \`posts\` table, its migration, and a code-first \`lesto()\` app,
 * wired into the LestoAppConfig that \`lesto dev\` boots. This is the whole
 * application — grow it by adding tables, migrations, routes, and pages.
 *
 * Routes read top-to-bottom like Hono/Express: one \`lesto()\` surface for both
 * API routes (\`.get\`/\`.post\`/…) and pages (\`.page\`), each handler a
 * \`(c) => response\` over the request context \`c\`.
 *
 * The HOME PAGE is NOT registered here — it lives at \`app/routes/page.tsx\` and is
 * auto-registered by Lesto's file-based routing (ADR 0023): drop a \`page.tsx\`
 * under \`app/routes/\` and its directory's URL becomes a route, no \`.page()\` call.
 * \`lesto dev\`/\`build\` scan that directory and compose every page onto THIS app.
 * Code-first routes (the \`/posts\` API below) and file routes live side by side on
 * the same router. Add a page by adding a file; add an API route by chaining \`.get\`.
 *
 * Two conventions worth seeing on day one:
 *   - Validation at the boundary (ADR 0005): the create handler runs the
 *     untrusted body through a Zod schema with \`c.valid\` before it touches the
 *     database. A bad body is a 422, never a crash. The schema is the only place
 *     input is checked; everything past it is typed and trusted.
 *   - Security on by default, declared in one place: the config's \`secure\` field.
 *     Per-client rate-limiting is on from the kernel default, and \`originCheck\`
 *     adds zero-token CSRF — a state-changing request from another origin is
 *     refused (it reads the browser's \`Sec-Fetch-Site\`), with no token plumbing.
 */

import { createDb, createTableSql, defineTable, dropTableSql, integer, text } from "@lesto/db";
import type { Db } from "@lesto/db";

import type { MigrationEntry } from "@lesto/migrate";

import { lesto } from "@lesto/web";
import { openSqlite } from "@lesto/runtime";
import type { LestoAppConfig } from "@lesto/kernel";

import { z } from "zod";

// The \`posts\` table — schema as a value backs both the migration's DDL
// and the inferred row type every query returns.
export const posts = defineTable("posts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  body: text("body").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

// The schema, version-stamped and idempotent — run on boot by the kernel.
const createPosts: MigrationEntry = {
  version: "001_create_posts",
  migration: {
    up: (schema) => {
      schema.execute(createTableSql(posts));
    },

    down: (schema) => {
      schema.execute(dropTableSql(posts));
    },
  },
};

// The input schema for a new post — semantic validation (non-blank, trimmed)
// lives here, not on the table (the table just says \`notNull()\`). This is the
// untrusted-input contract; see ADR 0005.
const NewPost = z.object({
  title: z.string().trim().min(1, "Title is required."),
  body: z.string().trim().min(1, "Body is required."),
});

// The app — built through a factory so its handlers close over the typed
// \`Db\`. No \`this\`, no global database connection, no inheritance for domain
// types. One \`lesto()\` surface for the whole app; grow it by chaining more
// \`.get\`/\`.post\` calls (and drop \`app/routes/*/page.tsx\` files for pages). The
// Cloudflare \`worker.ts\` builds its own minimal edge twin of this (the island
// home page, no SQLite \`/posts\`) — see its header for why and how to light the
// data routes on the edge over D1.
function buildApp(db: Db) {
  return (
    lesto()
      // Security is declared on the config below (\`secure\`), not wired here — so
      // this surface stays pure routes + pages.
      // The hydration runtime: \`lesto build\`/\`dev\` bundle \`app/islands/\` into
      // this \`/client.js\` (the Preact dialect — see \`ui\` below), and every page
      // gets the head module tag that boots it.
      .client("/client.js")
      // The home page is NOT registered here — it lives at \`app/routes/page.tsx\`
      // and Lesto's file-based routing composes it onto this app automatically.
      .get("/posts", async (c) => {
        const rows = await db.select().from(posts).orderBy(posts.id, "asc").all();

        return c.json({ posts: rows });
      })
      // POST /posts. \`c.valid\` proves the shape (or throws a 422); past it,
      // \`input\` is a typed \`{ title: string; body: string }\` we can trust.
      .post("/posts", async (c) => {
        const input = c.valid(NewPost);

        const now = new Date().toISOString();

        const post = await db
          .insert(posts)
          .values({ title: input.title, body: input.body, createdAt: now, updatedAt: now })
          .returning()
          .get();

        return c.json({ post }, 201);
      })
  );
}

// The driver seam: \`@lesto/runtime\`'s \`openSqlite\` boots better-sqlite3 under
// Node and falls back to the built-in \`bun:sqlite\` under Bun — the framework
// owns that, so the app never has to. The same handle backs the kernel (which
// runs migrations) and the typed \`@lesto/db\` the handlers query through.
const { db: handle } = await openSqlite("lesto.db");
const db = createDb(handle);

const config: LestoAppConfig = {
  db: handle,
  app: buildApp(db),
  migrations: [createPosts],
  // Security, declared in one place (ADR 0016). Per-client rate-limiting is ALREADY
  // on by the kernel default; \`originCheck\` layers zero-token CSRF over it — a
  // cross-site POST/PUT/PATCH/DELETE is refused at the door (it reads the browser's
  // \`Sec-Fetch-Site\`). Add \`cors\` / the signed-token \`csrf\`, retune \`rateLimit\`,
  // or set \`secure: false\` to opt out entirely.
  secure: { originCheck: {} },
  // The headline default (ADR 0011 Increment 3): \`preact\` ships a ~10 KB island
  // client. The single \`ui.dialect\` key drives BOTH the client bundle's
  // \`react\`→\`preact/compat\` alias (read by \`lesto dev\`/\`build\`) and — for a
  // bespoke worker — the server renderer. Switch to \`"react"\` to opt out.
  ui: { dialect: "preact" },
};

export default config;
`;
}

/**
 * `app/islands/counter.tsx` — the one island the starter ships (ADR 0011).
 *
 * One `defineIsland` default-export per file is the convention `lesto build`/`dev`
 * discover and bundle into `/client.js`. A deferred (`ssr: false`) island: the
 * server paints its fallback, the Preact client mounts the live component fresh —
 * the sound pairing while the CLI server renders React (full server-side Preact is
 * estate's bespoke whole-process-aliased path). The `useState` button is inert
 * until hydration, so a working click is the visible proof the island came alive.
 */
export function islandCounter(): string {
  return `import { useState } from "react";
import type { ReactElement } from "react";

import { defineIsland } from "@lesto/ui";

/** A trivial interactive component: the local count proves hydration is live. */
function Counter({ start }: { start: number }): ReactElement {
  const [n, setN] = useState(start);

  return (
    <button type="button" data-testid="counter" onClick={() => setN((value) => value + 1)}>
      count: {n}
    </button>
  );
}

/** Deferred island: server paints the fallback, the client mounts Counter fresh. */
export default defineIsland({
  name: "Counter",
  component: Counter,
  fallback: ({ start }) => <button type="button" data-testid="counter">count: {start}</button>,
});
`;
}

/**
 * `app/routes/page.tsx` — the file-routed home page, authored in JSX (ADR 0023).
 *
 * This is the headline "drop a file → it routes" convention, visible on day one: a
 * `page.tsx` at the convention root (`app/routes/`) registers the URL `/`, with no
 * `.page()` call in `lesto.app.ts`. `lesto dev`/`build` scan `app/routes/` and
 * compose every page onto the app, wrapped in its layout chain (`layout.tsx`).
 *
 * It renders the Counter island — the same deferred-hydration proof the starter
 * has always shipped, now reached through the file-routing path. Its `load` runs on
 * the server and the component's props are INFERRED from it via
 * `PageProps<typeof load>` (declared once, no restated interface — the shape
 * `lesto g page` emits and the examples use).
 */
export function routePage(): string {
  return `import type { ReactNode } from "react";

import type { PageDef, PageProps } from "@lesto/web";

import Counter from "../islands/counter";

/**
 * The server load. Pulled out as a top-level \`const\` so the component's props are
 * INFERRED from its return via \`PageProps<typeof load>\` — declared once, with no
 * restated interface. Returns the island's starting count.
 */
const load = () => ({ start: 0 });

/**
 * The default export IS the \`PageDef\` the file-route applier registers at \`/\`.
 * The Counter island is inert until the client bundle hydrates it — a working
 * click is the visible proof the island came alive on the Preact runtime.
 */
const page: PageDef<"/", PageProps<typeof load>> = {
  load,

  component: ({ start }: PageProps<typeof load>): ReactNode => (
    <main>
      <h1>Welcome to Lesto</h1>

      <p>
        This page is <strong>file-routed</strong>: it lives at{" "}
        <code>app/routes/page.tsx</code> and registers the URL <code>/</code> with no{" "}
        <code>.page()</code> call. Add a page by adding a file under{" "}
        <code>app/routes/</code>.
      </p>

      <Counter start={start} />
    </main>
  ),

  metadata: () => ({
    title: "Welcome to Lesto",
    description: "A file-routed home page over the Lesto starter.",
  }),
};

export default page;
`;
}

/**
 * `app/routes/layout.tsx` — the file-route convention's root layout (ADR 0023).
 *
 * Dropping a `layout.tsx` at the convention root wraps EVERY page discovered under
 * `app/routes/`. The applier composes it around each page's component
 * automatically — no `.layout()` call, no per-page wiring. It is an ordinary
 * component handed the page (or a deeper layout) as `children`.
 */
export function routeLayout(): string {
  return `import type { ReactNode } from "react";

/** Wrap every file-routed page in a shared shell — the convention's root layout. */
export default function RootLayout({ children }: { children: ReactNode }): ReactNode {
  return <div data-app-shell>{children}</div>;
}
`;
}

/**
 * `AGENTS.md` — the open agent-onboarding file (the standard `create-next-app`,
 * Vercel, and the broader ecosystem now ship). A coding agent dropped into the
 * project reads this to learn the conventions before touching code.
 *
 * `CLAUDE.md` re-points at this one file so there is a single source of truth.
 */
export function agentsMd(name: string): string {
  return `# ${name} — agent guide

This is a [Lesto](https://lesto.run) app. Lesto is a batteries-included fullstack
TypeScript framework (ESM, run directly — no build step for the source).

## Commands

- \`bun run dev\` — start the dev server (\`lesto dev\`). Boots the app, runs
  migrations, and serves request dispatch.
- \`bun run build\` — build the client bundle and prerender (\`lesto build\`).
- \`lesto deploy --cloudflare\` — prerender to \`out/\` and \`wrangler deploy\` the
  Worker (\`worker.ts\`).

## Layout

- \`lesto.app.ts\` — the app: tables (\`@lesto/db\`), migrations, and a code-first
  \`lesto()\` app with \`.get\`/\`.post\` API routes. The DB handle is opened here.
- \`app/routes/\` — **file-based routing** (ADR 0023). A \`page.tsx\` makes its
  directory's URL a route; \`layout.tsx\` wraps every page at or below it. A
  \`[param]\` directory is a dynamic segment, \`[...rest]\` a catch-all. Drop a file
  to add a route — no manual registration.
- \`app/islands/\` — client-interactive components (\`defineIsland\`), one default
  export per file. The build bundles these into \`/client.js\`; the rest of the page
  is server-rendered.
- \`lesto.sites.ts\` — the declared sites (dynamic/static zones).
- \`worker.ts\` + \`wrangler.jsonc\` — the Cloudflare edge deploy.

## Conventions

- **TypeScript + ESM.** Source runs directly; \`type: "module"\`.
- **Validation at the boundary.** Untrusted input (request bodies) is validated
  with a Zod schema via \`c.valid(Schema)\` before it is trusted — never deeper.
- **Security on by default.** \`secure: { originCheck: {} }\` in \`lesto.app.ts\`
  adds header-based CSRF; per-client rate-limiting is on by the kernel default.
- **Pages infer their props.** Author a top-level \`const load = ...\` and type the
  component with \`PageProps<typeof load>\` — declare the shape once.
- **Islands hydrate on the client.** A component is interactive only if it is a
  \`defineIsland\` under \`app/islands/\`; everything else is server-only.

## Adding things

- A page: \`app/routes/<path>/page.tsx\` (default-export a \`PageDef\`).
- An API route: chain \`.get(path, handler)\` / \`.post(...)\` in \`lesto.app.ts\`.
- A table: \`defineTable(...)\` in \`lesto.app.ts\` plus a \`MigrationEntry\`.
- An interactive widget: \`app/islands/<name>.tsx\` (default-export \`defineIsland\`).
`;
}

/**
 * `CLAUDE.md` — Claude Code's project file. It defers to `AGENTS.md` so the
 * conventions live in exactly one place (the open standard) rather than drifting
 * across two files.
 */
export function claudeMd(name: string): string {
  return `# ${name}

See [\`AGENTS.md\`](./AGENTS.md) for this project's commands, layout, and
conventions — it is the single source of truth for working in this codebase, for
Claude Code and any other coding agent alike.
`;
}

/**
 * `lesto.sites.ts` — the project's declared sites, mirroring `lesto.app.ts`.
 *
 * `lesto build`/`dev` read its default export. A single dynamic site at `/` runs
 * the whole app live; grow it (static zones, multiple origins) as the app does.
 * Its presence is also what keeps `lesto build` from crashing — a missing
 * `lesto.sites.ts` is tolerated (app-only dispatch), but shipping one is the
 * starting point every real app grows from.
 */
export function lestoSites(): string {
  return `import type { Site } from "@lesto/sites";

/**
 * One dynamic site at the root: every route runs live through the app's handler.
 * Add static zones (\`render: "static"\` with a \`pages\` list) or extra origins
 * here as the app grows.
 */
const sites: Site[] = [{ name: "app", render: "dynamic", basePath: "/" }];

export default sites;
`;
}

/** `tsconfig.json` for the scaffolded app: strict, ESM, bundler resolution. */
export function tsconfig(): string {
  const config = {
    compilerOptions: {
      target: "ES2023",
      // DOM for the island's browser APIs (`useState` over a real button), ES2023
      // for the server. The client bundle is compiled by `Bun.build`, not tsc.
      lib: ["ES2023", "DOM", "DOM.Iterable"],
      module: "ESNext",
      moduleResolution: "Bundler",
      verbatimModuleSyntax: true,
      isolatedModules: true,
      resolveJsonModule: true,
      strict: true,
      jsx: "react-jsx",
      types: ["node"],
      skipLibCheck: true,
    },
    include: ["lesto.app.ts", "lesto.sites.ts", "worker.ts", "app"],
  };

  return `${JSON.stringify(config, null, 2)}\n`;
}

/**
 * `worker.ts` — the Cloudflare Worker entry, the scaffold's edge twin.
 *
 * Lesto's dispatcher is pure, so the Worker is a thin adapter (ADR 0002):
 * `toFetchHandler` turns the app's `handle` into `fetch(Request) => Response`, and
 * `withAssets` serves the prerendered `out/` files from the Static Assets binding
 * first, falling through to the live app.
 *
 * This builds its OWN minimal `lesto()` app rather than importing `lesto.app.ts` —
 * the same edge-twin split `examples/estate` makes — because `lesto.app.ts` opens a
 * filesystem SQLite handle (`openSqlite`, via the native `better-sqlite3` addon) at
 * module scope, which a Worker has no filesystem for. So the edge serves the
 * island home page (the deploy's hydratable proof); to run the SQLite-backed
 * `/posts` routes on the edge too, wire a Cloudflare D1 binding and build the full
 * `buildApp(db)` over `@lesto/db`'s D1 adapter (see `examples/estate`).
 *
 * The deferred island still hydrates: `lesto build` shipped the Preact `/client.js`
 * into `out/`, served here from `ASSETS`, and the deferred island mounts fresh on
 * the client over the React server fallback (ADR 0008's deferred pairing) — so no
 * Preact server alias is needed here; the Worker server-renders React.
 *
 *   lesto deploy --cloudflare        # builds out/, then `wrangler deploy`
 */
export function worker(): string {
  return `import { createElement } from "react";

import { toFetchHandler, withAssets } from "@lesto/cloudflare";
import type { AssetExecutionContext, AssetFetcher } from "@lesto/cloudflare";

import { lesto } from "@lesto/web";

import Counter from "./app/islands/counter";

/** The bindings this Worker is configured with (see wrangler.jsonc). */
interface Env {
  readonly ASSETS: AssetFetcher;
}

// The edge twin of \`lesto.app.ts\`'s home page — the same client module tag and
// Counter island, no SQLite-backed \`/posts\` (the Worker has no filesystem DB).
// Built ONCE at module scope (per isolate) and reused across every request.
const app = lesto()
  .client("/client.js")
  .page("/", {
    component: () =>
      createElement(
        "main",
        null,
        createElement("h1", null, "Welcome to Lesto"),
        createElement(Counter, { start: 0 }),
      ),
  });

const handler = toFetchHandler((method, path, options) => app.handle(method, path, options));

export default {
  fetch(request: Request, env: Env, ctx: AssetExecutionContext): Promise<Response> {
    // Static files from \`out/\` first (cached at the PoP); the live app for the
    // rest. \`env.ASSETS\` is per-request, so this thin wrap happens every time; the
    // handler it wraps is the cached, isolate-lifetime one above.
    return withAssets(env.ASSETS, handler)(request, ctx);
  },
};
`;
}

/**
 * `wrangler.jsonc` — the Cloudflare deploy config (`lesto deploy --cloudflare`).
 *
 * The minimal wiring: `nodejs_compat` (the app's runtime leans on `node:*`), the
 * `worker.ts` entry, and the Static Assets binding rooted at `out/` (what `lesto
 * build` prerenders — the marketing HTML and the island `/client.js`). The binding
 * MUST be named `ASSETS`: that is the binding `worker.ts` reads as `env.ASSETS`.
 *
 * `name` seeds the `*.workers.dev` subdomain; rename it (and run `wrangler deploy`)
 * to publish under your own. `compatibility_date` pins the Workers runtime
 * semantics — bump it deliberately. This is JSONC: comments and trailing commas
 * are allowed, so the file documents itself in place.
 */
export function wranglerConfig(name: string): string {
  return `{
	// Generated by \`create-lesto\`. The minimal Cloudflare deploy config; see the
	// README's "Deploy to Cloudflare" section. Run: lesto deploy --cloudflare
	"name": ${JSON.stringify(name)},
	"main": "worker.ts",
	"compatibility_date": "2026-06-01",
	// node:crypto / node:* the app's runtime reaches for; off, the bundle fails.
	"compatibility_flags": [
		"nodejs_compat",
	],
	// The prerendered static site (\`lesto build\` → out/): served first at the PoP,
	// a miss falls through to the Worker. The binding name MUST be \`ASSETS\` — that
	// is what \`worker.ts\` reads as \`env.ASSETS\`.
	"assets": {
		"directory": "./out",
		"binding": "ASSETS",
	},
}
`;
}

/** `.gitignore` — keep build artefacts and the local SQLite file out of git. */
export function gitignore(): string {
  return ["node_modules/", "*.db", "*.db-journal", "dist/", "out/", ".DS_Store", ""].join("\n");
}

/** `README.md` — how to run the freshly scaffolded app. */
export function readme(name: string): string {
  return `# ${name}

A Lesto app — batteries included.

## Develop

\`\`\`sh
bun install
bun run dev
\`\`\`

\`lesto dev\` loads \`lesto.app.ts\` (which default-exports the app config) and
boots it: the kernel runs migrations and stands up request dispatch over
the typed \`@lesto/db\` handle the route handlers query through.

## Deploy to Cloudflare

\`\`\`sh
lesto deploy --cloudflare
\`\`\`

This prerenders the static site into \`out/\` and runs \`wrangler deploy\` —
shipping the Worker (\`worker.ts\`) and its bound Static Assets in one atomic,
Cloudflare-versioned step. \`worker.ts\` fronts the app through
\`@lesto/cloudflare\`'s \`toFetchHandler\` + \`withAssets\`, serving the prerendered
files first and the live app second.

A Worker has no filesystem SQLite, so \`worker.ts\` builds a minimal edge twin
of the home page (the hydrating island) rather than importing \`lesto.app.ts\`
(which opens a local SQLite handle at module scope). To run the \`/posts\` data
routes on the edge too, wire a Cloudflare D1 binding (see \`wrangler.jsonc\` and
the \`examples/estate\` reference in the Lesto source) and build the full app over
\`@lesto/db\`'s D1 adapter. Edit \`wrangler.jsonc\`'s \`name\` to pick your
\`*.workers.dev\` subdomain, then:

\`\`\`sh
wrangler login        # one-time, authenticates wrangler against your account
lesto deploy --cloudflare
\`\`\`

## Structure

- \`lesto.app.ts\` — the whole app: a \`posts\` table (defined via
  \`@lesto/db\`'s \`defineTable\`), its migration, and a code-first \`lesto()\`
  app built through a closure factory, with \`.get("/posts")\` /
  \`.post("/posts")\` route handlers.
- The \`POST /posts\` handler validates the request body at the boundary with
  a Zod schema via \`c.valid\` — a bad body is a 422, never a crash.
  See \`docs/adr/0005-validation-at-the-boundary.md\` in the Lesto source.
- Security is on by default, declared via the config's \`secure\` field: per-client
  rate-limiting comes from the kernel default, and \`secure: { originCheck: {} }\`
  adds zero-token, header-based CSRF — cross-site state-changing requests are
  refused. Note a non-browser client (e.g. \`curl\`) sends no \`Sec-Fetch-Site\`, so
  it is refused too — pass \`Sec-Fetch-Site: same-origin\` when testing by hand.
`;
}
