/**
 * The starter's files, as pure functions of the project name.
 *
 * Each function returns one file's contents as a string. They are
 * deliberately pure and side-effect free: `scaffold` owns all I/O, these
 * own all content, so the generated bytes are tested directly without
 * touching a disk.
 *
 * The app they emit is small but REAL — it boots on `@lesto/kernel`'s
 * `createApp` with a `posts` table (defined as a `@lesto/db` value), a
 * migration that runs `createTableSql(posts)`, and a code-first `lesto()`
 * app whose handlers query via `@lesto/db`. Mirrors the shape of the
 * canonical blog example (`examples/blog`) and the rest of the
 * post-ADR-0004 codebase.
 */

/**
 * The `@lesto/*` packages a scaffolded app depends on, by directory name under
 * `packages/`.
 *
 * `@lesto/cli` is the `lesto` binary `lesto dev`/`build` runs (its absence was a
 * silent break — blocker #9); `@lesto/assets` is the client-bundle pipeline the
 * island build needs in the app's graph; `@lesto/cloudflare` is the edge adapter
 * the deploy template's `worker.ts` fronts the app with (`lesto deploy
 * --cloudflare`); `@lesto/styles` is the Tailwind CSS pipeline the CLI lazily
 * imports to compile `app/styles/app.css` → `out/styles.css` (ADR 0037 — it is the
 * CLI's optional peer, so the app must carry it to light the CSS build). The rest
 * are the app's own runtime (db/kernel/migrate/runtime, the web router, the UI engine).
 */
export const LESTO_PACKAGES = [
  "@lesto/cli",
  "@lesto/assets",
  "@lesto/cloudflare",
  "@lesto/db",
  "@lesto/env",
  "@lesto/kernel",
  "@lesto/migrate",
  "@lesto/runtime",
  // `lesto.sites.ts` does `import type { Site } from "@lesto/sites"`; without this
  // dep the scaffolded app's type import 404s on a standalone (non-monorepo) install.
  "@lesto/sites",
  "@lesto/styles",
  "@lesto/ui",
  "@lesto/web",
] as const;

/**
 * The Tailwind v4 train the scaffolded app pins (ADR 0037). It MUST match the
 * `@tailwindcss/*` engine `@lesto/styles` depends on: `tailwindcss` is the PEER the
 * app's `@import "tailwindcss"` resolves, and the engine `@lesto/styles` owns
 * compiles against it — a divergent major would mismatch the engine and the app's CSS.
 */
const TAILWINDCSS_RANGE = "^4.3.0";

/**
 * The shadcn/ui runtime stack a scaffolded app ships so it is a *generic* shadcn
 * project on day one (ADR 0037 Phase 2): `clsx` + `tailwind-merge` back the `cn()`
 * helper (`app/lib/utils.ts`) every shadcn component imports; `tw-animate-css` is
 * the v4 animation layer the theme `@import`s (the successor to `tailwindcss-animate`);
 * `lucide-react` is the icon set `components.json` selects (`iconLibrary: "lucide"`).
 * `tailwind-merge` v3 is the Tailwind-v4-aware line — a v2 merge would mis-resolve v4
 * utilities. These are plain npm deps (NOT `@lesto/*`), so they sit beside `react`.
 */
export const SHADCN_DEPS = {
  clsx: "^2.1.1",
  "tailwind-merge": "^3.3.1",
  "tw-animate-css": "^1.3.4",
  "lucide-react": "^0.515.0",
} as const;

/**
 * Resolve a `@lesto/*` package name to the dependency specifier the scaffold pins
 * it at.
 *
 * Two implementations live in `scaffold.ts`: `publishedRangePin` (the default — a
 * published `^0.x` range an outsider installs from the registry) and
 * `fileColonPin` (a `file:` path at the in-repo package, selected by
 * `create-lesto --local` for in-monorepo dev before anything is published). The
 * resolver is injected so a test can pin to a fake specifier and the publish
 * decision lives in exactly one place.
 */
export type LestoDepResolver = (pkg: (typeof LESTO_PACKAGES)[number]) => string;

/**
 * Coerce a project name into a valid npm package name for the `package.json`
 * `name` field. `validate-npm-package-name` requires lowercase and forbids a
 * leading `.`/`_`, but the project/directory name is laxer (`assertValidName`
 * permits uppercase and a leading `_`/`.`), so the manifest name is DERIVED rather
 * than used verbatim — a `MyApp` directory still yields a valid `"myapp"` manifest.
 * An input that sanitizes to empty (e.g. `"__"`) falls back to the default name.
 */
export function toPackageName(name: string): string {
  // Lowercase, drop any char outside npm's allowed set, then strip a leading `.`/`_`.
  // (The `create` flow pre-restricts the name to `[A-Za-z0-9._-]`, but this helper is
  // exported and may be called directly, so it stays valid for any input.)
  const lowered = name
    .toLowerCase()
    .replace(/[^a-z0-9._-]/g, "")
    .replace(/^[._]+/, "");

  return lowered.length > 0 ? lowered : "lesto-app";
}

/**
 * `package.json` for the scaffolded app: starter deps + a `lesto dev` script.
 *
 * The `@lesto/*` specifiers come from the injected `lestoDep` resolver (the
 * published `^0.x` range by default, a `file:` pin under `--local`), keeping this
 * a pure function of its inputs. The app ships `preact` (the ~10 KB island client the Preact dialect
 * aliases `react` to) AND `react`/`react-dom` (the server still renders React —
 * see `lesto.app.ts`'s `ui: { dialect: "preact" }`). The `name` field is run
 * through {@link toPackageName} so an uppercase directory name still yields a
 * registry-valid manifest name.
 */
export function packageJson(name: string, lestoDep: LestoDepResolver): string {
  const lestoDeps = Object.fromEntries(LESTO_PACKAGES.map((pkg) => [pkg, lestoDep(pkg)]));

  const manifest = {
    name: toPackageName(name),
    version: "0.0.0",
    type: "module",
    private: true,
    // A scaffolded app is the user's own private project, not a Lesto package — so
    // it declares `UNLICENSED` rather than inheriting Lesto's MIT. The author
    // changes this to whatever license their project ships under.
    license: "UNLICENSED",

    scripts: {
      dev: "lesto dev",
      build: "lesto build",
    },

    dependencies: {
      ...lestoDeps,
      // The native SQLite addon `@lesto/runtime`'s `openSqlite` boots. Pinned to the
      // SAME `^11.10.0` train the framework itself depends on and tests against
      // (`@lesto/migrate`/`content-store`/`integration`), NOT a newer major — the
      // scaffold must not run ahead of the engine its driver is verified against.
      "better-sqlite3": "^11.10.0",
      // The Tailwind v4 engine `@lesto/styles` compiles the app's CSS against — the
      // PEER the app's `@import "tailwindcss"` resolves (ADR 0037). Pinned to the same
      // train as the engine `@lesto/styles` owns.
      tailwindcss: TAILWINDCSS_RANGE,
      // The Preact dialect (`ui.dialect: "preact"`) renders BOTH halves through
      // Preact: `preact` aliases the island client's `react` to `preact/compat` for
      // the ~10 KB bundle, and `preact-render-to-string` is the SERVER renderer
      // `@lesto/web` loads for that dialect (`@lesto/ui` marks it an optional peer,
      // so the app that picks the dialect must supply it). `react`/`react-dom` remain
      // for the JSX runtime the page components compile against.
      preact: "^10.29.2",
      "preact-render-to-string": "^6",
      react: "^19",
      "react-dom": "^19",
      // The shadcn/ui stack (ADR 0037 Phase 2): cn() = clsx + tailwind-merge, the
      // tw-animate-css v4 layer the theme imports, and the lucide icon set.
      ...SHADCN_DEPS,
      zod: "^4.0.0",
    },
  };

  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/**
 * `lesto.app.ts` — the project root's entrypoint.
 *
 * It default-exports a `LestoAppConfig` (the `{ db, app, migrations }` object
 * `createApp` accepts), which `@lesto/cli`'s `lesto dev` loads and boots.
 */
export function lestoApp(): string {
  return `/**
 * The app: a \`posts\` table, its migration, and a code-first \`lesto()\` app,
 * wired into the LestoAppConfig that \`lesto dev\` boots. This is the whole
 * application — grow it by adding tables, migrations, routes, and pages.
 *
 * Routes read top-to-bottom like Hono/Express: one \`lesto()\` surface for both
 * API routes (\`.get\`/\`.post\`/…) and pages (\`.page\`), each handler a
 * \`(c) => response\` over the request context \`c\`.
 *
 * The HOME PAGE is NOT registered here — it lives at \`app/routes/page.tsx\` and is
 * auto-registered by Lesto's file-based routing (ADR 0023): drop a \`page.tsx\`
 * under \`app/routes/\` and its directory's URL becomes a route, no \`.page()\` call.
 * \`lesto dev\`/\`build\` scan that directory and compose every page onto THIS app.
 * Code-first routes (the \`/posts\` API below) and file routes live side by side on
 * the same router. Add a page by adding a file; add an API route by chaining \`.get\`.
 *
 * Two conventions worth seeing on day one:
 *   - Validation at the boundary (ADR 0005): the create handler runs the
 *     untrusted body through a Zod schema with \`c.valid\` before it touches the
 *     database. A bad body is a 422, never a crash. The schema is the only place
 *     input is checked; everything past it is typed and trusted.
 *   - Security on by default, declared in one place: the config's \`secure\` field.
 *     Per-client rate-limiting is on from the kernel default, and \`originCheck\`
 *     adds zero-token CSRF — a state-changing request from another origin is
 *     refused (it reads the browser's \`Sec-Fetch-Site\`), with no token plumbing.
 */

import { createDb, createTableSql, defineTable, dropTableSql, integer, text } from "@lesto/db";
import type { Db } from "@lesto/db";

import type { MigrationEntry } from "@lesto/migrate";

import { lesto } from "@lesto/web";
import { openSqlite } from "@lesto/runtime";
import type { LestoAppConfig } from "@lesto/kernel";

import { z } from "zod";

import { env } from "./env";

// The \`posts\` table — schema as a value backs both the migration's DDL
// and the inferred row type every query returns.
export const posts = defineTable("posts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  body: text("body").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

// The schema, version-stamped and idempotent — run on boot by the kernel.
const createPosts: MigrationEntry = {
  version: "001_create_posts",
  migration: {
    up: (schema) => {
      schema.execute(createTableSql(posts));
    },

    down: (schema) => {
      schema.execute(dropTableSql(posts));
    },
  },
};

// A migration's up() can carry DATA, not just schema — it runs arbitrary SQL.
// This seeds a few starter posts so \`GET /posts\` returns content on first run
// (instead of an empty list that reads as broken). Delete this migration, and
// drop these rows, once you have your own data.
const seedPosts: MigrationEntry = {
  version: "002_seed_posts",
  migration: {
    up: (schema) => {
      schema.execute(
        "INSERT INTO posts (title, body, created_at, updated_at) VALUES" +
          " ('Hello, Lesto', 'Your first post — edit or delete it in lesto.app.ts.', '2026-01-01T00:00:00.000Z', '2026-01-01T00:00:00.000Z')," +
          " ('Batteries included', 'Queue, cache, auth, and mail all live on the database — no Redis.', '2026-01-01T00:00:00.000Z', '2026-01-01T00:00:00.000Z')," +
          " ('Agent-native', 'Drive this app from Claude over MCP, the CLI, or code.', '2026-01-01T00:00:00.000Z', '2026-01-01T00:00:00.000Z')",
      );
    },

    down: (schema) => {
      schema.execute("DELETE FROM posts WHERE created_at = '2026-01-01T00:00:00.000Z'");
    },
  },
};

// The input schema for a new post — semantic validation (non-blank, trimmed)
// lives here, not on the table (the table just says \`notNull()\`). This is the
// untrusted-input contract; see ADR 0005.
const NewPost = z.object({
  title: z.string().trim().min(1, "Title is required."),
  body: z.string().trim().min(1, "Body is required."),
});

// The app — built through a factory so its handlers close over the typed
// \`Db\`. No \`this\`, no global database connection, no inheritance for domain
// types. One \`lesto()\` surface for the whole app; grow it by chaining more
// \`.get\`/\`.post\` calls (and drop \`app/routes/*/page.tsx\` files for pages). The
// Cloudflare \`worker.ts\` builds its own minimal edge twin of this (the island
// home page, no SQLite \`/posts\`) — see its header for why and how to light the
// data routes on the edge over D1.
function buildApp(db: Db) {
  return (
    lesto()
      // Security is declared on the config below (\`secure\`), not wired here — so
      // this surface stays pure routes + pages.
      // The hydration runtime: \`lesto build\`/\`dev\` bundle \`app/islands/\` into
      // this \`/client.js\` (the Preact dialect — see \`ui\` below), and every page
      // gets the head module tag that boots it.
      .client("/client.js")
      // The stylesheet (ADR 0037): \`lesto build\`/\`dev\` compile \`ui.css\`
      // (\`app/styles/app.css\`, see \`ui\` below) → \`out/styles.css\`, and every page
      // gets this \`<link rel="stylesheet">\`. A stable name, like \`/client.js\`.
      .styles("/styles.css")
      // The home page is NOT registered here — it lives at \`app/routes/page.tsx\`
      // and Lesto's file-based routing composes it onto this app automatically.
      .get("/posts", async (c) => {
        const rows = await db.select().from(posts).orderBy(posts.id, "asc").all();

        return c.json({ posts: rows });
      })
      // POST /posts. \`c.valid\` proves the shape (or throws a 422); past it,
      // \`input\` is a typed \`{ title: string; body: string }\` we can trust.
      .post("/posts", async (c) => {
        const input = c.valid(NewPost);

        const now = new Date().toISOString();

        const post = await db
          .insert(posts)
          .values({ title: input.title, body: input.body, createdAt: now, updatedAt: now })
          .returning()
          .get();

        return c.json({ post }, 201);
      })
  );
}

// The driver seam: \`@lesto/runtime\`'s \`openSqlite\` boots better-sqlite3 under
// Node and falls back to the built-in \`bun:sqlite\` under Bun — the framework
// owns that, so the app never has to. The same handle backs the kernel (which
// runs migrations) and the typed \`@lesto/db\` the handlers query through. The DB
// file comes from the typed env (\`env.LESTO_DB\`, default \`lesto.db\`) — see \`env.ts\`.
const { db: handle } = await openSqlite(env.LESTO_DB);
const db = createDb(handle);

const config: LestoAppConfig = {
  db: handle,
  app: buildApp(db),
  migrations: [createPosts, seedPosts],
  // Security, declared in one place (ADR 0016). Per-client rate-limiting is ALREADY
  // on by the kernel default; \`originCheck\` layers zero-token CSRF over it — a
  // cross-site POST/PUT/PATCH/DELETE is refused at the door (it reads the browser's
  // \`Sec-Fetch-Site\`). Add \`cors\` / the signed-token \`csrf\`, retune \`rateLimit\`,
  // or set \`secure: false\` to opt out entirely.
  secure: { originCheck: {} },
  // The headline default (ADR 0011 Increment 3): \`preact\` ships a ~10 KB island
  // client. The single \`ui.dialect\` key drives BOTH the client bundle's
  // \`react\`→\`preact/compat\` alias (read by \`lesto dev\`/\`build\`) and — for a
  // bespoke worker — the server renderer. Switch to \`"react"\` to opt out.
  //
  // \`ui.css\` (ADR 0037) is the Tailwind v4 entry the CLI compiles to
  // \`out/styles.css\`. Its presence enables the CSS build; delete the key (and
  // \`app/styles/app.css\`) to ship no stylesheet. The build is read only by the CLI.
  ui: { dialect: "preact", css: "app/styles/app.css" },
};

export default config;
`;
}

/**
 * `app/styles/app.css` — the Tailwind v4 + shadcn/ui CSS entry (ADR 0037 Phase 2).
 *
 * `lesto build`/`dev` compile this to `out/styles.css` (the `ui.css` key in
 * `lesto.app.ts` points here) and inject it via `.styles("/styles.css")`. This is
 * the canonical shadcn v4 theme — `@import "tailwindcss"`, the `tw-animate-css`
 * layer, the `.dark` `@custom-variant`, the full OKLCH `:root`/`.dark` token sets
 * (`new-york` style, `neutral` base), the `@theme inline` block that exposes those
 * tokens as utilities (`bg-background`, `text-foreground`, …), and the `@layer base`
 * defaults — so a scaffolded app IS a generic shadcn project: `lesto add <name>`
 * drops components straight in. The scanner gotcha leads the file because it is the
 * one thing that surprises newcomers: Tailwind reads `app/` as PLAIN TEXT.
 */
export function stylesApp(): string {
  return `/*
 * Your Tailwind v4 + shadcn/ui stylesheet. \`lesto build\`/\`dev\` compile it to
 * \`out/styles.css\` (wired by \`ui.css\` in lesto.app.ts) and every page links it via
 * \`.styles(...)\`. The OKLCH tokens below are shadcn's \`neutral\` theme; edit them (or
 * run \`npx shadcn theme\`) to recolor, and toggle \`.dark\` on \`<html>\` for dark mode.
 *
 * SCANNER GOTCHA: Tailwind finds utilities by scanning your \`app/\` source as PLAIN
 * TEXT — it never runs your code. So write COMPLETE static class strings:
 *
 *   ✅ <div className="bg-primary text-primary-foreground" />
 *   ❌ <div className={\`bg-\${color}-600\`} />   // the scanner can't see this
 *
 * For genuinely runtime-dynamic classes, list them so the scanner keeps them:
 *   @source inline("bg-red-600 bg-green-600 bg-blue-600");
 */
@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

:root {
  --radius: 0.625rem;
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.145 0 0);
  --popover: oklch(1 0 0);
  --popover-foreground: oklch(0.145 0 0);
  --primary: oklch(0.205 0 0);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.97 0 0);
  --secondary-foreground: oklch(0.205 0 0);
  --muted: oklch(0.97 0 0);
  --muted-foreground: oklch(0.556 0 0);
  --accent: oklch(0.97 0 0);
  --accent-foreground: oklch(0.205 0 0);
  --destructive: oklch(0.577 0.245 27.325);
  --border: oklch(0.922 0 0);
  --input: oklch(0.922 0 0);
  --ring: oklch(0.708 0 0);
  --chart-1: oklch(0.646 0.222 41.116);
  --chart-2: oklch(0.6 0.118 184.704);
  --chart-3: oklch(0.398 0.07 227.392);
  --chart-4: oklch(0.828 0.189 84.429);
  --chart-5: oklch(0.769 0.188 70.08);
  --sidebar: oklch(0.985 0 0);
  --sidebar-foreground: oklch(0.145 0 0);
  --sidebar-primary: oklch(0.205 0 0);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.97 0 0);
  --sidebar-accent-foreground: oklch(0.205 0 0);
  --sidebar-border: oklch(0.922 0 0);
  --sidebar-ring: oklch(0.708 0 0);
}

.dark {
  --background: oklch(0.145 0 0);
  --foreground: oklch(0.985 0 0);
  --card: oklch(0.205 0 0);
  --card-foreground: oklch(0.985 0 0);
  --popover: oklch(0.205 0 0);
  --popover-foreground: oklch(0.985 0 0);
  --primary: oklch(0.922 0 0);
  --primary-foreground: oklch(0.205 0 0);
  --secondary: oklch(0.269 0 0);
  --secondary-foreground: oklch(0.985 0 0);
  --muted: oklch(0.269 0 0);
  --muted-foreground: oklch(0.708 0 0);
  --accent: oklch(0.269 0 0);
  --accent-foreground: oklch(0.985 0 0);
  --destructive: oklch(0.704 0.191 22.216);
  --border: oklch(1 0 0 / 10%);
  --input: oklch(1 0 0 / 15%);
  --ring: oklch(0.556 0 0);
  --chart-1: oklch(0.488 0.243 264.376);
  --chart-2: oklch(0.696 0.17 162.48);
  --chart-3: oklch(0.769 0.188 70.08);
  --chart-4: oklch(0.627 0.265 303.9);
  --chart-5: oklch(0.645 0.246 16.439);
  --sidebar: oklch(0.205 0 0);
  --sidebar-foreground: oklch(0.985 0 0);
  --sidebar-primary: oklch(0.488 0.243 264.376);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.269 0 0);
  --sidebar-accent-foreground: oklch(0.985 0 0);
  --sidebar-border: oklch(1 0 0 / 10%);
  --sidebar-ring: oklch(0.556 0 0);
}

@theme inline {
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`;
}

/**
 * `components.json` — the shadcn/ui project manifest (ADR 0037 Phase 2).
 *
 * Its presence is what makes a scaffolded app a *generic* shadcn project: the
 * shadcn CLI (`npx shadcn add <name>`, which `lesto add` delegates to in TW8) reads
 * this to know the style, the CSS entry, the base color, the icon set, and — via
 * `aliases` resolved against `tsconfig.json`'s `@/*` path — where to write each
 * component. `tailwind.config: ""` is correct for v4 (config-less, the theme lives
 * in `app/styles/app.css`). The aliases point at the in-app tree (`@/* → ./app/*`),
 * so components land under `app/components/ui` and `cn()` resolves at `@/lib/utils`.
 */
export function componentsJson(): string {
  const manifest = {
    $schema: "https://ui.shadcn.com/schema.json",
    style: "new-york",
    // Lesto server-renders plain React, not React Server Components.
    rsc: false,
    tsx: true,
    tailwind: {
      // Empty: Tailwind v4 is config-less — the theme lives in the CSS entry below.
      config: "",
      css: "app/styles/app.css",
      baseColor: "neutral",
      cssVariables: true,
      prefix: "",
    },
    iconLibrary: "lucide",
    aliases: {
      components: "@/components",
      ui: "@/components/ui",
      utils: "@/lib/utils",
      lib: "@/lib",
      hooks: "@/hooks",
    },
  };

  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/**
 * `app/lib/utils.ts` — the `cn()` class-name helper every shadcn component imports.
 *
 * `clsx` resolves conditional/array class inputs; `tailwind-merge` then de-conflicts
 * the result so a later Tailwind utility wins over an earlier one (e.g. `cn("p-2",
 * "p-4")` → `"p-4"`). Imported as `@/lib/utils` via the `@/*` tsconfig path. The
 * `ClassValue` type is a TYPE-only import — the scaffolded tsconfig sets
 * `verbatimModuleSyntax`, so a value import of a type would fail to compile.
 */
export function libUtils(): string {
  return `import { clsx } from "clsx";
import type { ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Merge class names the shadcn way: \`clsx\` flattens conditional inputs, then
 * \`tailwind-merge\` resolves conflicting Tailwind utilities so the last one wins.
 */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
`;
}

/**
 * `env.ts` — the project's typed, validated environment (`@lesto/env`).
 *
 * `defineEnv` validates the environment ONCE at boot into a frozen, fully-typed
 * object: a missing or malformed var fails fast with a coded error naming every
 * problem, rather than surfacing as an `undefined` deep in a handler. The starter
 * wires one real knob — `LESTO_DB`, the SQLite file `lesto.app.ts` opens — so the
 * pattern is visible on day one; add your own (`envField.string()` for a required
 * secret, `.port()`, `.boolean()`, `.oneOf([...])`) as the app grows. `lesto.app.ts`
 * reads `env.LESTO_DB` rather than `process.env` directly.
 */
export function env(): string {
  return `import { defineEnv, envField } from "@lesto/env";

import { clientEnv } from "./env.client";

/**
 * The typed environment, SPLIT into \`server\` and \`client\` halves. Read each value
 * off \`env\` (e.g. \`env.LESTO_DB\`, \`env.PUBLIC_APP_NAME\`) instead of \`process.env\`:
 * it is validated and typed, and a bad value fails at boot, not mid-request. Every
 * \`envField\` chains \`.optional()\` or \`.default(value)\`; a field with neither is
 * REQUIRED (boot throws if unset).
 *
 * SERVER vs CLIENT (the leak boundary):
 *   - \`server\` vars (secrets, the DB path) NEVER reach the browser. Read a server
 *     value in an \`app/islands/*\` component and it throws \`ENV_SERVER_LEAK\` LOUD +
 *     EARLY — a secret can't slip into client code.
 *   - \`client\` vars MUST be named \`PUBLIC_*\` (the leak contract). They live in the
 *     browser-safe \`env.client.ts\` (imported as \`clientEnv\`), so ONE schema feeds
 *     three places: this server validation, the island's \`defineClientEnv\`, and the
 *     bundler that inlines the values. \`lesto build\`/\`dev\` reads \`env.client.ts\` and
 *     bakes the \`PUBLIC_*\` literals into island code — no \`process.env\` in the browser.
 *
 * WHERE VALUES COME FROM:
 *   - Local dev: \`lesto dev\`/\`build\` run under Bun, which auto-loads \`.env\` and
 *     \`.env.local\` into \`process.env\` — so put secrets in \`.env.local\` (it is
 *     gitignored; commit a \`.env.example\` of the NAMES instead).
 *   - Cloudflare deploy: a Worker has no \`process.env\`. Read config off the Worker
 *     \`env\` binding (set with \`wrangler secret put NAME\`) and validate it the same
 *     way with \`defineEnv(schema, workerEnv)\` — pass the binding as the 2nd arg.
 */
export const env = defineEnv({
  server: {
    // The SQLite database file the app opens (see \`lesto.app.ts\`). Defaults to
    // \`lesto.db\` in the project root; point it elsewhere with \`LESTO_DB=/path.db\`.
    LESTO_DB: envField.string().default("lesto.db"),
    // Add server-only secrets here — e.g. SESSION_SECRET: envField.string().
    // They are validated at boot and NEVER shipped to the browser.
  },
  // The \`PUBLIC_*\` client schema, shared with the island + the bundler (env.client.ts).
  client: clientEnv,
});
`;
}

/**
 * `env.client.ts` — the project's PUBLIC (`PUBLIC_*`) env schema, declared ONCE.
 *
 * This module imports ONLY `@lesto/env/client` (the browser-safe surface, by
 * construction free of any server secret), so it is the single source of truth three
 * places share: `env.ts` validates it as its `client` half, the island validates it
 * with `defineClientEnv`, and `lesto build`/`dev` reads its `clientEnv` export to
 * inline the validated `PUBLIC_*` values into the island bundle. Keeping it separate
 * from `env.ts` (which validates the server half on import) is what lets the bundler
 * read the client schema WITHOUT running server validation. Every key MUST be `PUBLIC_*`.
 */
export function envClient(): string {
  return `import { envField } from "@lesto/env/client";
import type { ClientSchema } from "@lesto/env/client";

/**
 * The PUBLIC config the app ships to the browser — every key MUST be \`PUBLIC_*\`. The
 * bundler inlines these into island code (\`lesto build\`/\`dev\`), so \`defineClientEnv\`
 * resolves them in the browser with no \`process.env\`. A \`.default()\` makes a var
 * optional; drop it for a REQUIRED one (a missing value then fails the build, not at
 * hydration). NEVER put a secret here — only \`PUBLIC_*\` names are accepted.
 */
export const clientEnv = {
  PUBLIC_APP_NAME: envField.string().default("Lesto app"),
} satisfies ClientSchema;
`;
}

/**
 * `app/islands/counter.tsx` — the one island the starter ships (ADR 0011).
 *
 * One `defineIsland` default-export per file is the convention `lesto build`/`dev`
 * discover and bundle into `/client.js`. A deferred (`ssr: false`) island: the
 * server paints its fallback, the Preact client mounts the live component fresh —
 * the sound pairing while the CLI server renders React (full server-side Preact is
 * estate's bespoke whole-process-aliased path). The `useState` button is inert
 * until hydration, so a working click is the visible proof the island came alive.
 *
 * It also reads PUBLIC config in the browser via `@lesto/env/client` — the safe
 * client surface, by construction free of any server secret. The bundler inlines the
 * `PUBLIC_*` subset (from `env.ts`'s `client` half), so `defineClientEnv` resolves to
 * the validated literal with no `process.env` in the browser. NEVER import `./env`
 * (the server schema) here — reaching a server var from an island throws
 * `ENV_SERVER_LEAK`; the bundler likewise refuses to inline a non-`PUBLIC_*` var.
 */
export function islandCounter(): string {
  return `import { useState } from "react";
import type { ReactElement } from "react";

import { defineIsland } from "@lesto/ui";
import { defineClientEnv } from "@lesto/env/client";

import { clientEnv } from "../../env.client";

// PUBLIC config, read in the browser from the SHARED \`env.client.ts\` schema (the same
// one \`env.ts\` validates and the bundler inlines). \`@lesto/env/client\` is the
// browser-safe surface: by construction it can hold no secret. NEVER import \`../../env\`
// (the server schema) here — reaching a server var from an island throws ENV_SERVER_LEAK.
const publicEnv = defineClientEnv(clientEnv);

/** A trivial interactive component: the local count proves hydration is live. */
function Counter({ start }: { start: number }): ReactElement {
  const [n, setN] = useState(start);

  return (
    <button
      type="button"
      data-testid="counter"
      title={publicEnv.PUBLIC_APP_NAME}
      onClick={() => setN((value) => value + 1)}
    >
      count: {n}
    </button>
  );
}

/** Deferred island: server paints the fallback, the client mounts Counter fresh. */
export default defineIsland({
  name: "Counter",
  component: Counter,
  fallback: ({ start }) => <button type="button" data-testid="counter">count: {start}</button>,
});
`;
}

/**
 * `app/routes/page.tsx` — the file-routed home page, authored in JSX (ADR 0023).
 *
 * This is the headline "drop a file → it routes" convention, visible on day one: a
 * `page.tsx` at the convention root (`app/routes/`) registers the URL `/`, with no
 * `.page()` call in `lesto.app.ts`. `lesto dev`/`build` scan `app/routes/` and
 * compose every page onto the app, wrapped in its layout chain (`layout.tsx`).
 *
 * It renders the Counter island — the same deferred-hydration proof the starter
 * has always shipped, now reached through the file-routing path. Its `load` runs on
 * the server and the component's props are INFERRED from it via
 * `PageProps<typeof load>` (declared once, no restated interface — the shape
 * `lesto g page` emits and the examples use).
 */
export function routePage(): string {
  return `import type { ReactNode } from "react";

import type { PageDef, PageProps } from "@lesto/web";

import Counter from "../islands/counter";

/**
 * The server load. Pulled out as a top-level \`const\` so the component's props are
 * INFERRED from its return via \`PageProps<typeof load>\` — declared once, with no
 * restated interface. Returns the island's starting count.
 */
const load = () => ({ start: 0 });

/**
 * The default export IS the \`PageDef\` the file-route applier registers at \`/\`.
 * The Counter island is inert until the client bundle hydrates it — a working
 * click is the visible proof the island came alive on the Preact runtime.
 */
const page: PageDef<"/", PageProps<typeof load>> = {
  load,

  component: ({ start }: PageProps<typeof load>): ReactNode => (
    <main>
      <h1>Welcome to Lesto</h1>

      <p>
        This page is <strong>file-routed</strong>: it lives at{" "}
        <code>app/routes/page.tsx</code> and registers the URL <code>/</code> with no{" "}
        <code>.page()</code> call. Add a page by adding a file under{" "}
        <code>app/routes/</code>.
      </p>

      <Counter start={start} />
    </main>
  ),

  metadata: () => ({
    title: "Welcome to Lesto",
    description: "A file-routed home page over the Lesto starter.",
  }),
};

export default page;
`;
}

/**
 * `app/routes/layout.tsx` — the file-route convention's root layout (ADR 0023).
 *
 * Dropping a `layout.tsx` at the convention root wraps EVERY page discovered under
 * `app/routes/`. The applier composes it around each page's component
 * automatically — no `.layout()` call, no per-page wiring. It is an ordinary
 * component handed the page (or a deeper layout) as `children`.
 */
export function routeLayout(): string {
  return `import type { ReactNode } from "react";

/** Wrap every file-routed page in a shared shell — the convention's root layout. */
export default function RootLayout({ children }: { children: ReactNode }): ReactNode {
  return <div data-app-shell>{children}</div>;
}
`;
}

/**
 * `AGENTS.md` — the open agent-onboarding file (the standard `create-next-app`,
 * Vercel, and the broader ecosystem now ship). A coding agent dropped into the
 * project reads this to learn the conventions before touching code.
 *
 * `CLAUDE.md` re-points at this one file so there is a single source of truth.
 */
export function agentsMd(name: string): string {
  return `# ${name} — agent guide

This is a [Lesto](https://lesto.run) app. Lesto is a batteries-included fullstack
TypeScript framework (ESM, run directly — no build step for the source).

## Commands

- \`bun run dev\` — start the dev server (\`lesto dev\`). Boots the app, runs
  migrations, and serves request dispatch.
- \`bun run build\` — build the client bundle and prerender (\`lesto build\`).
- \`lesto deploy --cloudflare\` — prerender to \`out/\` and \`wrangler deploy\` the
  Worker (\`worker.ts\`).

## Layout

- \`lesto.app.ts\` — the app: tables (\`@lesto/db\`), migrations, and a code-first
  \`lesto()\` app with \`.get\`/\`.post\` API routes. The DB handle is opened here.
- \`env.ts\` — the typed, validated environment (\`@lesto/env\`), split \`server\` /
  \`client\`. \`defineEnv\` checks it at boot; read values off \`env\` (e.g.
  \`env.LESTO_DB\`), not \`process.env\`. Server vars never reach the browser (reading
  one in an island throws \`ENV_SERVER_LEAK\`); \`client\` vars are \`PUBLIC_*\` and an
  island reads them via \`@lesto/env/client\`.
- \`app/routes/\` — **file-based routing** (ADR 0023). A \`page.tsx\` makes its
  directory's URL a route; \`layout.tsx\` wraps every page at or below it. A
  \`[param]\` directory is a dynamic segment, \`[...rest]\` a catch-all. Drop a file
  to add a route — no manual registration.
- \`app/islands/\` — client-interactive components (\`defineIsland\`), one default
  export per file. The build bundles these into \`/client.js\`; the rest of the page
  is server-rendered.
- \`app/styles/app.css\` — the **Tailwind v4** entry (\`ui.css\` in \`lesto.app.ts\`).
  \`lesto build\`/\`dev\` compile it to \`out/styles.css\` and link it on every page.
  Tailwind scans \`app/\` as PLAIN TEXT, so write complete static class strings (not
  \`bg-\${x}\`); see the comment in that file.
- \`lesto.sites.ts\` — the declared sites (dynamic/static zones).
- \`worker.ts\` + \`wrangler.jsonc\` — the Cloudflare edge deploy.

## Conventions

- **TypeScript + ESM.** Source runs directly; \`type: "module"\`.
- **Validation at the boundary.** Untrusted input (request bodies) is validated
  with a Zod schema via \`c.valid(Schema)\` before it is trusted — never deeper.
- **Security on by default.** \`secure: { originCheck: {} }\` in \`lesto.app.ts\`
  adds header-based CSRF; per-client rate-limiting is on by the kernel default.
- **Pages infer their props.** Author a top-level \`const load = ...\` and type the
  component with \`PageProps<typeof load>\` — declare the shape once.
- **Islands hydrate on the client.** A component is interactive only if it is a
  \`defineIsland\` under \`app/islands/\`; everything else is server-only.

## Adding things

- A page: \`app/routes/<path>/page.tsx\` (default-export a \`PageDef\`).
- An API route: chain \`.get(path, handler)\` / \`.post(...)\` in \`lesto.app.ts\`.
- A table: \`defineTable(...)\` in \`lesto.app.ts\` plus a \`MigrationEntry\`.
- An interactive widget: \`app/islands/<name>.tsx\` (default-export \`defineIsland\`).
`;
}

/**
 * `CLAUDE.md` — Claude Code's project file. It defers to `AGENTS.md` so the
 * conventions live in exactly one place (the open standard) rather than drifting
 * across two files.
 */
export function claudeMd(name: string): string {
  return `# ${name}

See [\`AGENTS.md\`](./AGENTS.md) for this project's commands, layout, and
conventions — it is the single source of truth for working in this codebase, for
Claude Code and any other coding agent alike.
`;
}

/**
 * `lesto.sites.ts` — the project's declared sites, mirroring `lesto.app.ts`.
 *
 * `lesto build`/`dev` read its default export. A single dynamic site at `/` runs
 * the whole app live; grow it (static zones, multiple origins) as the app does.
 * Its presence is also what keeps `lesto build` from crashing — a missing
 * `lesto.sites.ts` is tolerated (app-only dispatch), but shipping one is the
 * starting point every real app grows from.
 */
export function lestoSites(): string {
  return `import type { Site } from "@lesto/sites";

/**
 * One dynamic site at the root: every route runs live through the app's handler.
 * Add static zones (\`render: "static"\` with a \`pages\` list) or extra origins
 * here as the app grows.
 */
const sites: Site[] = [{ name: "app", render: "dynamic", basePath: "/" }];

export default sites;
`;
}

/** `tsconfig.json` for the scaffolded app: strict, ESM, bundler resolution. */
export function tsconfig(): string {
  const config = {
    compilerOptions: {
      target: "ES2023",
      // DOM for the island's browser APIs (`useState` over a real button), ES2023
      // for the server. The client bundle is compiled by `Bun.build`, not tsc.
      lib: ["ES2023", "DOM", "DOM.Iterable"],
      module: "ESNext",
      moduleResolution: "Bundler",
      verbatimModuleSyntax: true,
      isolatedModules: true,
      resolveJsonModule: true,
      strict: true,
      jsx: "react-jsx",
      types: ["node"],
      skipLibCheck: true,
      // The shadcn `@/*` alias (ADR 0037 Phase 2): app code lives under `app/`, so
      // `@/lib/utils` → `app/lib/utils` and `@/components/ui` → `app/components/ui`.
      // `components.json`'s aliases resolve against this, so `npx shadcn add` writes
      // each component into the in-app tree. TS 5 resolves `paths` without `baseUrl`
      // (relative to this file) under `moduleResolution: "Bundler"`.
      paths: {
        "@/*": ["./app/*"],
      },
    },
    include: ["env.ts", "lesto.app.ts", "lesto.sites.ts", "worker.ts", "app"],
  };

  return `${JSON.stringify(config, null, 2)}\n`;
}

/**
 * `worker.ts` — the Cloudflare Worker entry, the scaffold's edge twin.
 *
 * Lesto's dispatcher is pure, so the Worker is a thin adapter (ADR 0002):
 * `toFetchHandler` turns the app's `handle` into `fetch(Request) => Response`, and
 * `withAssets` serves the prerendered `out/` files from the Static Assets binding
 * first, falling through to the live app.
 *
 * This builds its OWN minimal `lesto()` app rather than importing `lesto.app.ts` —
 * the same edge-twin split `examples/estate` makes — because `lesto.app.ts` opens a
 * filesystem SQLite handle (`openSqlite`, via the native `better-sqlite3` addon) at
 * module scope, which a Worker has no filesystem for. So the edge serves the
 * island home page (the deploy's hydratable proof); to run the SQLite-backed
 * `/posts` routes on the edge too, wire a Cloudflare D1 binding and build the full
 * `buildApp(db)` over `@lesto/db`'s D1 adapter (see `examples/estate`).
 *
 * The deferred island still hydrates: `lesto build` shipped the Preact `/client.js`
 * into `out/`, served here from `ASSETS`, and the deferred island mounts fresh on
 * the client over the React server fallback (ADR 0008's deferred pairing) — so no
 * Preact server alias is needed here; the Worker server-renders React.
 *
 *   lesto deploy --cloudflare        # builds out/, then `wrangler deploy`
 */
export function worker(): string {
  return `import { toFetchHandler, withAssets } from "@lesto/cloudflare";
import type { AssetExecutionContext, AssetFetcher } from "@lesto/cloudflare";

import { lesto } from "@lesto/web";

import home from "./app/routes/page";
import RootLayout from "./app/routes/layout";

/** The bindings this Worker is configured with (see wrangler.jsonc). */
interface Env {
  readonly ASSETS: AssetFetcher;
}

// The edge entry mounts the SAME file-routed home as \`lesto dev\`: \`home\` is the
// \`PageDef\` default-exported by \`app/routes/page.tsx\`, wrapped by the \`RootLayout\`
// from \`app/routes/layout.tsx\` — so editing those files changes BOTH the dev page
// and the deployed Worker, with no hand-built twin to drift out of sync. A Worker
// has no filesystem to discover routes at request time, so each route is registered
// EXPLICITLY here: add a \`.page("/path", def)\` for every new file route you want at
// the edge (richer SQLite-backed routes stay server-side — the Worker has no
// filesystem DB). Built ONCE at module scope (per isolate), reused every request.
const app = lesto()
  .client("/client.js")
  // The stylesheet \`lesto build\` compiled to \`out/styles.css\` (ADR 0037), served
  // here from \`ASSETS\` and linked into every page — the edge twin of the dev link.
  .styles("/styles.css")
  .layout(RootLayout)
  .page("/", home);

const handler = toFetchHandler((method, path, options) => app.handle(method, path, options));

export default {
  fetch(request: Request, env: Env, ctx: AssetExecutionContext): Promise<Response> {
    // Static files from \`out/\` first (cached at the PoP); the live app for the
    // rest. \`env.ASSETS\` is per-request, so this thin wrap happens every time; the
    // handler it wraps is the cached, isolate-lifetime one above.
    return withAssets(env.ASSETS, handler)(request, ctx);
  },
};
`;
}

/**
 * `wrangler.jsonc` — the Cloudflare deploy config (`lesto deploy --cloudflare`).
 *
 * The minimal wiring: `nodejs_compat` (the app's runtime leans on `node:*`), the
 * `worker.ts` entry, and the Static Assets binding rooted at `out/` (what `lesto
 * build` prerenders — the marketing HTML and the island `/client.js`). The binding
 * MUST be named `ASSETS`: that is the binding `worker.ts` reads as `env.ASSETS`.
 *
 * `name` seeds the `*.workers.dev` subdomain; rename it (and run `wrangler deploy`)
 * to publish under your own. `compatibility_date` pins the Workers runtime
 * semantics — bump it deliberately. This is JSONC: comments and trailing commas
 * are allowed, so the file documents itself in place.
 */
export function wranglerConfig(name: string): string {
  return `{
	// Generated by \`create-lesto\`. The minimal Cloudflare deploy config; see the
	// README's "Deploy to Cloudflare" section. Run: lesto deploy --cloudflare
	"name": ${JSON.stringify(name)},
	"main": "worker.ts",
	"compatibility_date": "2026-06-01",
	// node:crypto / node:* the app's runtime reaches for; off, the bundle fails.
	"compatibility_flags": [
		"nodejs_compat",
	],
	// The prerendered static site (\`lesto build\` → out/): served first at the PoP,
	// a miss falls through to the Worker. The binding name MUST be \`ASSETS\` — that
	// is what \`worker.ts\` reads as \`env.ASSETS\`.
	"assets": {
		"directory": "./out",
		"binding": "ASSETS",
	},
}
`;
}

/**
 * `.gitignore` — keep build artefacts, the local SQLite file, and SECRETS out of git.
 *
 * The secrets lines matter and cover BOTH local-dev secret channels: \`lesto dev\`/
 * \`build\` run under Bun, which auto-loads \`.env\`/\`.env.local\` into \`process.env\`
 * (where \`env.ts\`'s \`defineEnv\` reads them); and \`wrangler dev\` reads local secrets
 * from \`.dev.vars\`. Both hold secrets and must never be committed. \`.env.example\` is
 * the exception — a committable, secret-free template of the variable NAMES.
 */
export function gitignore(): string {
  return [
    "node_modules/",
    "*.db",
    "*.db-journal",
    "dist/",
    "out/",
    ".DS_Store",
    "",
    "# Secrets — local env (Bun loads .env/.env.local) + wrangler (.dev.vars). Never commit.",
    ".env",
    ".env.*",
    "!.env.example",
    ".dev.vars",
    ".dev.vars.*",
    "",
  ].join("\n");
}

/** `README.md` — how to run the freshly scaffolded app. */
export function readme(name: string): string {
  return `# ${name}

A Lesto app — batteries included.

## Develop

\`\`\`sh
bun install
bun run dev
\`\`\`

\`lesto dev\` loads \`lesto.app.ts\` (which default-exports the app config) and
boots it: the kernel runs migrations and stands up request dispatch over
the typed \`@lesto/db\` handle the route handlers query through.

## Try it

With \`bun run dev\` running, the app serves on http://localhost:3000. The
\`posts\` table is seeded with a few starter rows on first boot (the
\`002_seed_posts\` migration in \`lesto.app.ts\`). Read them from the JSON API:

\`\`\`sh
curl http://localhost:3000/posts
\`\`\`

Now create one. State-changing requests are CSRF-guarded by default
(\`secure: { originCheck: {} }\`), which reads the browser's \`Sec-Fetch-Site\`
header — a non-browser client like \`curl\` sends none, so it must set it
explicitly or the request is refused with a 403:

\`\`\`sh
curl -X POST http://localhost:3000/posts \\
  -H 'Content-Type: application/json' \\
  -H 'Sec-Fetch-Site: same-origin' \\
  -d '{"title":"My first post","body":"Hello from curl."}'
\`\`\`

A blank \`title\` or \`body\` is rejected at the boundary with a 422, never a
crash — that is the Zod \`c.valid\` check in \`lesto.app.ts\`. Read the list again
and your new post is there.

## Deploy to Cloudflare

\`\`\`sh
lesto deploy --cloudflare
\`\`\`

This prerenders the static site into \`out/\` and runs \`wrangler deploy\` —
shipping the Worker (\`worker.ts\`) and its bound Static Assets in one atomic,
Cloudflare-versioned step. \`worker.ts\` fronts the app through
\`@lesto/cloudflare\`'s \`toFetchHandler\` + \`withAssets\`, serving the prerendered
files first and the live app second.

A Worker has no filesystem SQLite, so \`worker.ts\` builds a minimal edge twin
of the home page (the hydrating island) rather than importing \`lesto.app.ts\`
(which opens a local SQLite handle at module scope). To run the \`/posts\` data
routes on the edge too, wire a Cloudflare D1 binding (see \`wrangler.jsonc\` and
the \`examples/estate\` reference in the Lesto source) and build the full app over
\`@lesto/db\`'s D1 adapter. Edit \`wrangler.jsonc\`'s \`name\` to pick your
\`*.workers.dev\` subdomain, then:

\`\`\`sh
wrangler login        # one-time, authenticates wrangler against your account
lesto deploy --cloudflare
\`\`\`

## Structure

- \`lesto.app.ts\` — the whole app: a \`posts\` table (defined via
  \`@lesto/db\`'s \`defineTable\`), its migration, and a code-first \`lesto()\`
  app built through a closure factory, with \`.get("/posts")\` /
  \`.post("/posts")\` route handlers.
- The \`POST /posts\` handler validates the request body at the boundary with
  a Zod schema via \`c.valid\` — a bad body is a 422, never a crash.
  See \`docs/adr/0005-validation-at-the-boundary.md\` in the Lesto source.
- Security is on by default, declared via the config's \`secure\` field: per-client
  rate-limiting comes from the kernel default, and \`secure: { originCheck: {} }\`
  adds zero-token, header-based CSRF — cross-site state-changing requests are
  refused. Note a non-browser client (e.g. \`curl\`) sends no \`Sec-Fetch-Site\`, so
  it is refused too — pass \`Sec-Fetch-Site: same-origin\` when testing by hand.
`;
}
