/**
 * The starter's files, as pure functions of the project name.
 *
 * Each function returns one file's contents as a string. They are
 * deliberately pure and side-effect free: `scaffold` owns all I/O, these
 * own all content, so the generated bytes are tested directly without
 * touching a disk.
 *
 * The app they emit is small but REAL — it boots on `@keel/kernel`'s
 * `createApp` with a `posts` table (defined as a `@keel/db` value), a
 * migration that runs `createTableSql(posts)`, and a code-first `keel()`
 * app whose handlers query via `@keel/db`. Mirrors the shape of the
 * canonical blog example (`examples/blog`) and the rest of the
 * post-ADR-0004 codebase.
 */

/**
 * The version specifier every `@keel/*` dependency is scaffolded with.
 *
 * A real npm dist-tag, resolvable by any package manager outside this
 * monorepo — deliberately NOT the `workspace:*` protocol, which only
 * resolves in-workspace.
 */
const keelDep = "latest";

/** `package.json` for the scaffolded app: starter deps + a `keel dev` script. */
export function packageJson(name: string): string {
  const manifest = {
    name,
    version: "0.0.0",
    type: "module",
    private: true,

    scripts: {
      dev: "keel dev",
    },

    dependencies: {
      // Resolvable specifiers for a freshly scaffolded app: `latest` is a
      // real npm dist-tag any package manager can install OUTSIDE this
      // monorepo. The `workspace:*` protocol resolves only within the
      // workspace, so a generated app would fail to install.
      "@keel/db": keelDep,
      "@keel/kernel": keelDep,
      "@keel/migrate": keelDep,
      "@keel/runtime": keelDep,
      "@keel/ui": keelDep,
      "@keel/web": keelDep,
      "better-sqlite3": "^11.10.0",
      react: "^19",
      "react-dom": "^19",
      zod: "^4.0.0",
    },
  };

  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/**
 * `keel.app.ts` — the project root's entrypoint.
 *
 * It default-exports a `KeelAppConfig` (the `{ db, app, migrations }` object
 * `createApp` accepts), which `@keel/cli`'s `keel dev` loads and boots.
 */
export function keelApp(): string {
  return `/**
 * The app: a \`posts\` table, its migration, and a code-first \`keel()\` app,
 * wired into the KeelAppConfig that \`keel dev\` boots. This is the whole
 * application — grow it by adding tables, migrations, routes, and pages.
 *
 * Routes read top-to-bottom like Hono/Express: one \`keel()\` surface for both
 * API routes (\`.get\`/\`.post\`/…) and pages (\`.page\`), each handler a
 * \`(c) => response\` over the request context \`c\`.
 *
 * Two conventions worth seeing on day one:
 *   - Validation at the boundary (ADR 0005): the create handler runs the
 *     untrusted body through a Zod schema with \`c.valid\` before it touches the
 *     database. A bad body is a 422, never a crash. The schema is the only place
 *     input is checked; everything past it is typed and trusted.
 *   - CSRF on by default: \`secureStack({ originCheck: {} })\` refuses a
 *     state-changing request that didn't come from this origin (it reads the
 *     browser's \`Sec-Fetch-Site\`), with no per-form token plumbing. The
 *     request-shaped batteries drop onto the chain via \`fromRequestMiddleware\`.
 */

import { createDb, createTableSql, defineTable, dropTableSql, integer, text } from "@keel/db";
import type { Db } from "@keel/db";

import type { MigrationEntry } from "@keel/migrate";

import { fromRequestMiddleware, keel } from "@keel/web";
import { openSqlite } from "@keel/runtime";
import { secureStack } from "@keel/kernel";
import type { KeelAppConfig } from "@keel/kernel";

import { z } from "zod";

// The \`posts\` table — schema as a value backs both the migration's DDL
// and the inferred row type every query returns.
export const posts = defineTable("posts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  body: text("body").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

// The schema, version-stamped and idempotent — run on boot by the kernel.
const createPosts: MigrationEntry = {
  version: "001_create_posts",
  migration: {
    up: (schema) => {
      schema.execute(createTableSql(posts));
    },

    down: (schema) => {
      schema.execute(dropTableSql(posts));
    },
  },
};

// The input schema for a new post — semantic validation (non-blank, trimmed)
// lives here, not on the table (the table just says \`notNull()\`). This is the
// untrusted-input contract; see ADR 0005.
const NewPost = z.object({
  title: z.string().trim().min(1, "Title is required."),
  body: z.string().trim().min(1, "Body is required."),
});

// The app — built through a factory so its handlers close over the typed
// \`Db\`. No \`this\`, no global database connection, no inheritance for domain
// types. One \`keel()\` surface for the whole app; grow it by chaining more
// \`.get\`/\`.post\`/\`.page\` calls.
function buildApp(db: Db) {
  return (
    keel()
      // Security batteries, on by default. \`originCheck\` is the zero-token CSRF
      // defense: a cross-site POST/PUT/PATCH/DELETE is refused at the door. Add
      // \`cors\`, \`rateLimit\`, or the signed-token \`csrf\` here as you need them.
      .use(...secureStack({ originCheck: {} }).map(fromRequestMiddleware))
      .get("/posts", async (c) => {
        const rows = await db.select().from(posts).orderBy(posts.id, "asc").all();

        return c.json({ posts: rows });
      })
      // POST /posts. \`c.valid\` proves the shape (or throws a 422); past it,
      // \`input\` is a typed \`{ title: string; body: string }\` we can trust.
      .post("/posts", async (c) => {
        const input = c.valid(NewPost);

        const now = new Date().toISOString();

        const post = await db
          .insert(posts)
          .values({ title: input.title, body: input.body, createdAt: now, updatedAt: now })
          .returning()
          .get();

        return c.json({ post }, 201);
      })
  );
}

// The driver seam: \`@keel/runtime\`'s \`openSqlite\` boots better-sqlite3 under
// Node and falls back to the built-in \`bun:sqlite\` under Bun — the framework
// owns that, so the app never has to. The same handle backs the kernel (which
// runs migrations) and the typed \`@keel/db\` the handlers query through.
const { db: handle } = await openSqlite("keel.db");
const db = createDb(handle);

const config: KeelAppConfig = {
  db: handle,
  app: buildApp(db),
  migrations: [createPosts],
};

export default config;
`;
}

/** `tsconfig.json` for the scaffolded app: strict, ESM, bundler resolution. */
export function tsconfig(): string {
  const config = {
    compilerOptions: {
      target: "ES2023",
      lib: ["ES2023"],
      module: "ESNext",
      moduleResolution: "Bundler",
      verbatimModuleSyntax: true,
      isolatedModules: true,
      resolveJsonModule: true,
      strict: true,
      jsx: "react-jsx",
      types: ["node"],
      skipLibCheck: true,
    },
    include: ["keel.app.ts"],
  };

  return `${JSON.stringify(config, null, 2)}\n`;
}

/** `.gitignore` — keep build artefacts and the local SQLite file out of git. */
export function gitignore(): string {
  return ["node_modules/", "*.db", "*.db-journal", "dist/", ".DS_Store", ""].join("\n");
}

/** `README.md` — how to run the freshly scaffolded app. */
export function readme(name: string): string {
  return `# ${name}

A Keel app — batteries included.

## Develop

\`\`\`sh
bun install
bun run dev
\`\`\`

\`keel dev\` loads \`keel.app.ts\` (which default-exports the app config) and
boots it: the kernel runs migrations and stands up request dispatch over
the typed \`@keel/db\` handle the route handlers query through.

## Structure

- \`keel.app.ts\` — the whole app: a \`posts\` table (defined via
  \`@keel/db\`'s \`defineTable\`), its migration, and a code-first \`keel()\`
  app built through a closure factory, with \`.get("/posts")\` /
  \`.post("/posts")\` route handlers.
- The \`POST /posts\` handler validates the request body at the boundary with
  a Zod schema via \`c.valid\` — a bad body is a 422, never a crash.
  See \`docs/adr/0005-validation-at-the-boundary.md\` in the Keel source.
- Security is on by default: \`secureStack({ originCheck: {} })\` refuses
  cross-site state-changing requests (zero-token, header-based CSRF). Note a
  non-browser client (e.g. \`curl\`) sends no \`Sec-Fetch-Site\`, so it is
  refused too — pass \`Sec-Fetch-Site: same-origin\` when testing by hand.
`;
}
