import { describe, it, expect } from "vitest";
import { z } from "zod";
import { generateTypes } from "../typegen";
import type { AnyCollection } from "../types";
import type { AnyTaxonomy, TaxonomySchema } from "../taxonomy";

// Helper to create test collections
function createCollection(
  name: string,
  schema: z.ZodObject<z.ZodRawShape>,
  overrides?: Partial<AnyCollection>,
): AnyCollection {
  return {
    name,
    directory: `content/${name}`,
    include: "**/*.md",
    schema: schema as unknown as AnyCollection["schema"],
    ...overrides,
  };
}

// Create enum taxonomy (simple string terms)
const createEnumTaxonomy = (name: string, terms: readonly string[]): AnyTaxonomy => ({
  name,
  terms,
});

// Create schema taxonomy (object terms with slug)
const createSchemaTaxonomy = (
  name: string,
  terms: Array<{ name: string; slug: string }>,
): AnyTaxonomy => ({
  name,
  schema: z.object({ name: z.string() }) as TaxonomySchema,
  terms,
});

describe("typegen", () => {
  describe("structure", () => {
    it("generates header comments", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain("// Auto-generated by @volo/content-core - DO NOT EDIT");
      expect(types).toContain(
        "// Types are inferred from your config using TypeScript's type system.",
      );
      expect(types).toContain(
        "// This works with ANY Standard Schema library (Zod, Valibot, ArkType, etc.)",
      );
    });

    it("imports config with default path", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain('import type config from "../docks.config";');
    });

    it("imports config with custom path", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col], [], { configPath: "../../custom.config" });

      expect(types).toContain('import type config from "../../custom.config";');
    });

    it("imports utility types from @volo/content-core", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain(
        'import type { GetEntryByName, GetSchemaByName } from "@volo/content-core";',
      );
    });
  });

  describe("type aliases", () => {
    it("generates entry type alias using GetEntryByName", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain('export type Posts = GetEntryByName<typeof config, "posts">;');
    });

    it("generates schema type alias using GetSchemaByName", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain('export type PostsSchema = GetSchemaByName<typeof config, "posts">;');
    });

    it("uses PascalCase for type names", () => {
      const col = createCollection("blog-posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain("export type BlogPosts = ");
      expect(types).toContain("export type BlogPostsSchema = ");
    });

    it("generates types for multiple collections", () => {
      const posts = createCollection("posts", z.object({ title: z.string() }));
      const pages = createCollection("pages", z.object({ content: z.string() }));
      const types = generateTypes([posts, pages]);

      expect(types).toContain('export type Posts = GetEntryByName<typeof config, "posts">;');
      expect(types).toContain('export type PostsSchema = GetSchemaByName<typeof config, "posts">;');
      expect(types).toContain('export type Pages = GetEntryByName<typeof config, "pages">;');
      expect(types).toContain('export type PagesSchema = GetSchemaByName<typeof config, "pages">;');
    });
  });

  describe("module augmentation", () => {
    it("augments CollectionRegistry", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain('declare module "@volo/content-core" {');
      expect(types).toContain("interface CollectionRegistry {");
    });

    it("references generated type aliases in registry", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain('"posts": { entry: Posts; schema: PostsSchema };');
    });

    it("includes all collections in registry", () => {
      const posts = createCollection("posts", z.object({ title: z.string() }));
      const pages = createCollection("pages", z.object({ content: z.string() }));
      const types = generateTypes([posts, pages]);

      expect(types).toContain('"posts": { entry: Posts; schema: PostsSchema };');
      expect(types).toContain('"pages": { entry: Pages; schema: PagesSchema };');
    });
  });

  describe("taxonomy support", () => {
    it("generates taxonomy registry entries for enum taxonomies", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const taxonomy = createEnumTaxonomy("categories", ["tech", "news"]);
      const types = generateTypes([col], [taxonomy]);

      expect(types).toContain("interface TaxonomyRegistry {");
      expect(types).toContain('"categories": "tech" | "news";');
    });

    it("generates taxonomy registry entries for schema taxonomies", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const taxonomy = createSchemaTaxonomy("categories", [
        { name: "Tech", slug: "tech" },
        { name: "News", slug: "news" },
      ]);
      const types = generateTypes([col], [taxonomy]);

      expect(types).toContain("interface TaxonomyRegistry {");
      expect(types).toContain('"categories": "tech" | "news";');
    });

    it("generates taxonomy type aliases", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const taxonomy = createEnumTaxonomy("categories", ["tech", "news"]);
      const types = generateTypes([col], [taxonomy]);

      expect(types).toContain('export type Categories = "tech" | "news";');
    });

    it("handles empty taxonomies", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const taxonomy = createEnumTaxonomy("categories", []);
      const types = generateTypes([col], [taxonomy]);

      expect(types).toContain('"categories": never;');
      expect(types).toContain("export type Categories = never;");
    });

    it("handles multiple taxonomies", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const categories = createEnumTaxonomy("categories", ["tech"]);
      const tags = createEnumTaxonomy("tags", ["js"]);
      const types = generateTypes([col], [categories, tags]);

      expect(types).toContain('"categories": "tech";');
      expect(types).toContain('"tags": "js";');
      expect(types).toContain('export type Categories = "tech";');
      expect(types).toContain('export type Tags = "js";');
    });
  });

  describe("MDX component types", () => {
    it("generates MDX component interface", () => {
      const col: AnyCollection = {
        ...createCollection("posts", z.object({ title: z.string() })),
        include: "**/*.mdx",
        mdx: {
          components: {
            Alert: "./src/components/Alert",
            Code: "./src/components/Code",
          },
        },
      };
      const types = generateTypes([col]);

      expect(types).toContain("// MDX Component Types");
      expect(types).toContain("export interface PostsComponents {");
      expect(types).toContain("Alert: typeof import('./src/components/Alert').default;");
      expect(types).toContain("Code: typeof import('./src/components/Code').default;");
    });

    it("skips MDX types when no components configured", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).not.toContain("MDX Component Types");
      expect(types).not.toContain("PostsComponents");
    });

    it("only generates MDX types for collections with components", () => {
      const mdxCol: AnyCollection = {
        ...createCollection("posts", z.object({ title: z.string() })),
        include: "**/*.mdx",
        mdx: {
          components: { Alert: "./src/components/Alert" },
        },
      };
      const regularCol = createCollection("pages", z.object({ title: z.string() }));
      const types = generateTypes([mdxCol, regularCol]);

      expect(types).toContain("PostsComponents");
      expect(types).not.toContain("PagesComponents");
    });

    it("escapes special characters in component names", () => {
      const col: AnyCollection = {
        ...createCollection("posts", z.object({ title: z.string() })),
        mdx: {
          components: {
            "custom-alert": "./components/CustomAlert",
          },
        },
      };
      const types = generateTypes([col]);

      expect(types).toContain(
        "\"custom-alert\": typeof import('./components/CustomAlert').default;",
      );
    });
  });

  describe("edge cases", () => {
    it("handles collection names requiring escaping", () => {
      const col = createCollection("my-posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain('GetEntryByName<typeof config, "my-posts">');
      expect(types).toContain('"my-posts": { entry: MyPosts; schema: MyPostsSchema };');
    });

    it("handles empty collections array", () => {
      const types = generateTypes([]);

      expect(types).toContain("interface CollectionRegistry {");
      expect(types).toContain("}");
    });

    it("handles collections with no include pattern", () => {
      const col: AnyCollection = {
        name: "posts",
        directory: "content/posts",
        schema: z.object({ title: z.string() }) as unknown as AnyCollection["schema"],
      };
      const types = generateTypes([col]);

      expect(types).toContain("export type Posts = ");
    });
  });

  describe("Standard Schema compatibility", () => {
    it("works with schemas from any library (type-level)", () => {
      // This test verifies the structure - actual type inference happens at compile time
      // The key is that we don't introspect the schema at runtime anymore
      const col = createCollection(
        "posts",
        z.object({
          title: z.string(),
          count: z.number(),
          published: z.boolean(),
          date: z.date(),
          tags: z.array(z.string()),
          metadata: z.record(z.string(), z.unknown()),
        }),
      );
      const types = generateTypes([col]);

      // The generated types use inference, not literal types
      expect(types).toContain("GetEntryByName<typeof config");
      expect(types).toContain("GetSchemaByName<typeof config");

      // Should NOT contain literal type representations
      expect(types).not.toContain("title: string");
      expect(types).not.toContain("count: number");
    });

    it("includes comment about Standard Schema compatibility", () => {
      const col = createCollection("posts", z.object({ title: z.string() }));
      const types = generateTypes([col]);

      expect(types).toContain("Zod, Valibot, ArkType");
    });
  });
});
